'use client';

import * as React from 'react';
import { useLocale } from 'next-intl';
import type { JournalDraft } from '@/lib/journal-api';

const content = {
  zh: { summary: '解读摘要', six: '六字段解读', claims: '主张与原文证据', figures: '图卡', faq: '常见问题', empty: '尚无内容，可以添加并保存为私有修订。', evidence: '展开原文证据', quote: '原文摘录', locator: '原文位置', claim: '主张', kind: '研究类别', figure: '图号', purpose: '图的用途', finding: '图中发现', question: '问题', answer: '回答', addClaim: '添加主张', addFigure: '添加图卡', addFaq: '添加问答', remove: '移除', experimental: '实验', simulation: '模拟', theoretical: '理论', review: '综述', other: '其他', core: { problem: '研究问题', insight: '核心洞见', method: '研究方法', results: '主要结果', limitations: '研究局限', reproducibility: '可复现性' } },
  en: { summary: 'Interpretation summary', six: 'Six-field interpretation', claims: 'Claims and source evidence', figures: 'Figure cards', faq: 'Frequently asked questions', empty: 'No content yet. Add and save a private revision.', evidence: 'Show source evidence', quote: 'Source excerpt', locator: 'Source location', claim: 'Claim', kind: 'Research type', figure: 'Figure number', purpose: 'Purpose', finding: 'Finding', question: 'Question', answer: 'Answer', addClaim: 'Add claim', addFigure: 'Add figure card', addFaq: 'Add question', remove: 'Remove', experimental: 'Experimental', simulation: 'Simulation', theoretical: 'Theoretical', review: 'Review', other: 'Other', core: { problem: 'Research question', insight: 'Core insight', method: 'Method', results: 'Results', limitations: 'Limitations', reproducibility: 'Reproducibility' } },
} as const;

type Evidence = { quote: string; locator: string };
const field = 'min-w-0 w-full border border-os-rule-paper bg-transparent p-3 text-os-ink';

export function JournalDraftEditor({ draft, readOnly, onChange }: { draft: JournalDraft; readOnly: boolean; onChange: (draft: JournalDraft) => void }) {
  const t = content[useLocale() === 'en' ? 'en' : 'zh'];
  function evidenceEditor(evidence: Evidence, update: (next: Evidence) => void) {
    return <details className="mt-4 border-t border-os-rule-paper pt-3"><summary className="min-h-10 cursor-pointer text-sm text-os-muted-paper">{t.evidence}</summary><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="grid gap-2 text-sm">{t.quote}<textarea readOnly={readOnly} value={evidence.quote} onChange={(event) => update({ ...evidence, quote: event.target.value })} className={field} /></label><label className="grid gap-2 text-sm">{t.locator}<textarea readOnly={readOnly} value={evidence.locator} onChange={(event) => update({ ...evidence, locator: event.target.value })} className={field} /></label></div></details>;
  }
  return <div className="mt-5 space-y-9">
    <section><h3 className="text-lg font-normal">{t.summary}</h3><textarea aria-label={t.summary} readOnly={readOnly} rows={4} value={draft.summary} onChange={(event) => onChange({ ...draft, summary: event.target.value })} className={`${field} mt-3`} /></section>
    <section><h3 className="text-lg font-normal">{t.six}</h3><div className="mt-3 grid gap-3 sm:grid-cols-2">{(Object.keys(t.core) as Array<keyof typeof t.core>).map((key, index) => <label className="grid gap-2 border border-os-rule-paper p-4 text-sm" key={key}><span className="text-xs text-os-muted-paper">0{index + 1} / 06</span><span className="font-medium">{t.core[key]}</span><textarea readOnly={readOnly} rows={3} value={draft.core[key] || ''} onChange={(event) => onChange({ ...draft, core: { ...draft.core, [key]: event.target.value } })} className={field} /></label>)}</div></section>
    <section><h3 className="text-lg font-normal">{t.claims}</h3>{draft.claims.length === 0 ? <p className="mt-3 text-sm text-os-muted-paper">{t.empty}</p> : null}<div className="mt-3 space-y-3">{draft.claims.map((claim, index) => <article className="border border-os-rule-paper p-4" key={index}><div className="flex items-start justify-between gap-3"><span className="text-xs text-os-muted-paper">{String(index + 1).padStart(2, '0')}</span>{!readOnly ? <button type="button" className="text-sm underline" onClick={() => onChange({ ...draft, claims: draft.claims.filter((_, i) => i !== index) })}>{t.remove}</button> : null}</div><label className="mt-3 grid gap-2 text-sm">{t.claim}<textarea readOnly={readOnly} value={claim.text} onChange={(event) => onChange({ ...draft, claims: draft.claims.map((item, i) => i === index ? { ...item, text: event.target.value } : item) })} className={field} /></label><label className="mt-3 grid gap-2 text-sm">{t.kind}<select disabled={readOnly} value={claim.kind} onChange={(event) => onChange({ ...draft, claims: draft.claims.map((item, i) => i === index ? { ...item, kind: event.target.value as typeof claim.kind } : item) })} className={field}>{(['experimental', 'simulation', 'theoretical', 'review', 'other'] as const).map((kind) => <option key={kind} value={kind}>{t[kind]}</option>)}</select></label>{evidenceEditor(claim.evidence, (evidence) => onChange({ ...draft, claims: draft.claims.map((item, i) => i === index ? { ...item, evidence } : item) }))}</article>)}</div>{!readOnly ? <button type="button" className="mt-3 min-h-11 border border-os-rule-paper px-4 text-sm" onClick={() => onChange({ ...draft, claims: [...draft.claims, { text: '', kind: 'other', evidence: { quote: '', locator: '' } }] })}>{t.addClaim}</button> : null}</section>
    <section><h3 className="text-lg font-normal">{t.figures}</h3>{draft.figures.length === 0 ? <p className="mt-3 text-sm text-os-muted-paper">{t.empty}</p> : null}<div className="mt-3 space-y-3">{draft.figures.map((figure, index) => <article className="border border-os-rule-paper p-4" key={index}><div className="flex items-start justify-between gap-3"><span className="text-xs text-os-muted-paper">{String(index + 1).padStart(2, '0')}</span>{!readOnly ? <button type="button" className="text-sm underline" onClick={() => onChange({ ...draft, figures: draft.figures.filter((_, i) => i !== index) })}>{t.remove}</button> : null}</div><div className="mt-3 grid gap-3 sm:grid-cols-3">{(['label', 'purpose', 'finding'] as const).map((key) => <label className="grid gap-2 text-sm" key={key}>{key === 'label' ? t.figure : t[key]}<textarea readOnly={readOnly} value={figure[key]} onChange={(event) => onChange({ ...draft, figures: draft.figures.map((item, i) => i === index ? { ...item, [key]: event.target.value } : item) })} className={field} /></label>)}</div>{evidenceEditor(figure.evidence, (evidence) => onChange({ ...draft, figures: draft.figures.map((item, i) => i === index ? { ...item, evidence } : item) }))}</article>)}</div>{!readOnly ? <button type="button" className="mt-3 min-h-11 border border-os-rule-paper px-4 text-sm" onClick={() => onChange({ ...draft, figures: [...draft.figures, { label: '', purpose: '', finding: '', evidence: { quote: '', locator: '' } }] })}>{t.addFigure}</button> : null}</section>
    <section><h3 className="text-lg font-normal">{t.faq}</h3>{draft.faq.length === 0 ? <p className="mt-3 text-sm text-os-muted-paper">{t.empty}</p> : null}<div className="mt-3 space-y-3">{draft.faq.map((faq, index) => <article className="border border-os-rule-paper p-4" key={index}><div className="flex items-start justify-between gap-3"><span className="text-xs text-os-muted-paper">{String(index + 1).padStart(2, '0')}</span>{!readOnly ? <button type="button" className="text-sm underline" onClick={() => onChange({ ...draft, faq: draft.faq.filter((_, i) => i !== index) })}>{t.remove}</button> : null}</div><label className="mt-3 grid gap-2 text-sm">{t.question}<input readOnly={readOnly} value={faq.question} onChange={(event) => onChange({ ...draft, faq: draft.faq.map((item, i) => i === index ? { ...item, question: event.target.value } : item) })} className={field} /></label><label className="mt-3 grid gap-2 text-sm">{t.answer}<textarea readOnly={readOnly} value={faq.answer} onChange={(event) => onChange({ ...draft, faq: draft.faq.map((item, i) => i === index ? { ...item, answer: event.target.value } : item) })} className={field} /></label>{evidenceEditor(faq.evidence, (evidence) => onChange({ ...draft, faq: draft.faq.map((item, i) => i === index ? { ...item, evidence } : item) }))}</article>)}</div>{!readOnly && draft.faq.length < 5 ? <button type="button" className="mt-3 min-h-11 border border-os-rule-paper px-4 text-sm" onClick={() => onChange({ ...draft, faq: [...draft.faq, { question: '', answer: '', evidence: { quote: '', locator: '' } }] })}>{t.addFaq}</button> : null}</section>
  </div>;
}
