'use client';
import * as React from 'react';
import { activateJournal, addJournalMember, listJournalMembers, removeJournalMember, transferJournalOwner, updateJournalHomepage, updateJournalMember, type JournalDashboard, type JournalMember } from '@/lib/journal-api';
import { shouldOfferHomepageActivation } from '@/lib/journal-workbench-model';
export function JournalGovernance({ data, reload }: { data: JournalDashboard; reload: () => Promise<void> }) {
  const [members, setMembers] = React.useState<JournalMember[]>([]); const [email, setEmail] = React.useState('');
  const [description, setDescription] = React.useState(data.journal.description ?? ''); const [newOwnerId, setNewOwnerId] = React.useState(''); const [reason, setReason] = React.useState('');
  const [message, setMessage] = React.useState(''); const [busy, setBusy] = React.useState(false); const inFlight = React.useRef(false);
  const loadMembers = React.useCallback(async () => { const result = await listJournalMembers(data.journal.id); setMembers(result.items); }, [data.journal.id]);
  React.useEffect(() => { void loadMembers().catch((cause) => setMessage(cause instanceof Error ? cause.message : '无法加载成员')); }, [loadMembers]);
  async function mutate(action: () => Promise<unknown>) {
    if (inFlight.current) return; inFlight.current = true; setBusy(true); setMessage('');
    try { await action(); await loadMembers(); await reload(); setMessage('已保存。'); }
    catch (cause) { setMessage(cause instanceof Error ? cause.message : '操作失败，请重试。'); }
    finally { inFlight.current = false; setBusy(false); }
  }
  const input = 'min-h-11 max-w-full border border-os-rule-paper bg-transparent px-3 text-sm disabled:opacity-50';
  return <details className="border-t border-os-rule-paper pt-5"><summary className="cursor-pointer text-lg">主页与成员管理</summary>
    <label className="mt-5 grid gap-2 text-sm">期刊简介<textarea rows={3} value={description} onChange={(event) => setDescription(event.target.value)} disabled={busy} className="border border-os-rule-paper bg-transparent p-3" /></label>
    <div className="mt-3 flex flex-wrap gap-3"><button className={input} disabled={busy} onClick={() => void mutate(() => updateJournalHomepage(data.journal.id, { revision: data.journal.revision ?? 0, description }))}>保存主页</button>{shouldOfferHomepageActivation(data.journal) ? <button className={input} disabled={busy} onClick={() => { if (window.confirm('确认首次公开期刊主页？此操作不会自动发布论文解读。')) void mutate(() => activateJournal(data.journal.id)); }}>首次公开期刊主页</button> : null}</div>
    <h3 className="mt-7 text-lg font-normal">期刊成员</h3><div className="flex flex-wrap gap-3"><input type="email" aria-label="添加编辑的邮箱" value={email} onChange={(event) => setEmail(event.target.value)} className={input} placeholder="已注册成员邮箱" disabled={busy} /><button className={input} disabled={busy || !email.trim()} onClick={() => void mutate(async () => { await addJournalMember(data.journal.id, { email: email.trim(), role: 'editor' }); setEmail(''); })}>添加编辑</button></div>
    {members.map((member) => <div key={member.userId} className="flex flex-wrap items-center gap-3 border-b border-os-rule-paper py-3"><span className="min-w-48 text-sm">{member.displayName || member.email}</span><select aria-label={`${member.displayName || member.email}的角色`} className={input} disabled={busy || member.role === 'owner'} value={member.role} onChange={(event) => void mutate(() => updateJournalMember(data.journal.id, member.userId, event.target.value as 'admin' | 'editor' | 'reviewer'))}><option value="admin">期刊管理员</option><option value="editor">编辑</option><option value="reviewer">审核人</option>{member.role === 'owner' ? <option value="owner">负责人</option> : null}</select>{member.role !== 'owner' ? <button className={input} disabled={busy} onClick={() => { if (window.confirm(`确认移除 ${member.displayName || member.email} 的期刊成员权限？`)) void mutate(() => removeJournalMember(data.journal.id, member.userId)); }}>移除成员</button> : null}</div>)}
    {data.membership.role === 'owner' ? <details className="mt-6 border border-os-rule-paper p-4"><summary>转移负责人</summary><p className="text-sm">转移后当前负责人降为期刊管理员，期刊进入重新核验。</p><label className="grid gap-2 text-sm">新负责人<select className={input} value={newOwnerId} disabled={busy} onChange={(event) => setNewOwnerId(event.target.value)}><option value="">选择已加入成员</option>{members.filter((member) => member.role !== 'owner').map((member) => <option key={member.userId} value={member.userId}>{member.displayName || member.email}</option>)}</select></label><label className="mt-3 grid gap-2 text-sm">转移原因<textarea value={reason} onChange={(event) => setReason(event.target.value)} disabled={busy} className="border border-os-rule-paper bg-transparent p-3" /></label><button className={`${input} mt-3`} disabled={busy || !newOwnerId || !reason.trim()} onClick={() => { const selected = members.find((member) => member.userId === newOwnerId); if (window.confirm(`确认转移给 ${selected?.displayName || selected?.email}，并触发期刊重新核验？`)) void mutate(() => transferJournalOwner(data.journal.id, { newOwnerId, reason: reason.trim() })); }}>确认转移</button></details> : null}
    {busy || message ? <p className="mt-4 text-sm" role="status">{busy ? '正在保存…' : message}</p> : null}</details>;
}
