'use client';
import Link from 'next/link';
import * as React from 'react';
import { ApiClientError } from '@/lib/api';
import { addJournalArticleSource, getJournalArticle, getJournalArticleSources, getJournalDashboard, recalculateJournalProcessingCapability, updateJournalArticleSourceRights, type ArticleProcessingCapability, type JournalArticle, type JournalArticleSourceRecord, type JournalRightsStatus, type JournalSourceConfidence, type JournalSourceHistoryEntry, type JournalSourceType } from '@/lib/journal-api';
import { editSourceEvidence, emptySourcePermissions, HERMES_DISCLOSURE, HERMES_PERMISSIONS, limitPermissions, RIGHTS_EXAMPLE, setHermesConsent, STATUS_PERMISSIONS, type SourcePermissions } from '@/lib/journal-rights-form';
const control = 'min-h-11 max-w-full border border-os-rule-paper bg-transparent px-3 text-sm disabled:opacity-50';
const statuses: Array<[JournalRightsStatus, string]> = [['unknown', '权限未知'], ['metadata_only_allowed', '仅允许书目信息'], ['abstract_processing_allowed', '允许摘要加工'], ['internal_processing_only', '仅内部解读'], ['public_summary_allowed', '允许公开文字解读'], ['figure_reuse_allowed', '允许公开使用原图'], ['derivative_illustration_allowed', '允许生成示意图'], ['full_public_processing_allowed', '允许完整加工与公开'], ['restricted_blocked', '限制或禁止使用']];
const confidences: Array<[JournalSourceConfidence, string]> = [['verified', '已核验'], ['editor_claimed', '编辑声明'], ['author_claimed', '作者声明'], ['publicly_accessible', '公开可访问'], ['machine_parsed_only', '仅机器解析'], ['conflict', '存在冲突'], ['expired', '已过期'], ['revoked', '已撤回']];
const sourceTypes: Array<[JournalSourceType, string]> = [['doi_metadata', 'DOI 书目信息'], ['abstract', '摘要'], ['public_full_text', '公开全文'], ['publisher_full_text', '出版商全文'], ['editor_uploaded_pdf', '编辑上传的 PDF'], ['author_material', '作者提供材料'], ['supplementary', '辅助材料'], ['figure_asset', '论文图片'], ['parsed_text', '解析文本'], ['ocr_visual_sidecar', '视觉辅助材料'], ['manual_note', '人工说明']];
type CurrentSource = Pick<JournalArticle['source'], 'kind' | 'url' | 'label'> & { artifactId?: string };
const fullTextTypes = new Set<JournalSourceType>(['public_full_text', 'publisher_full_text', 'editor_uploaded_pdf', 'author_material', 'parsed_text', 'ocr_visual_sidecar']);
export function sourceBindingIssue(current: CurrentSource, sourceType: JournalSourceType, url: string, active: boolean): string | null {
  if (!active) return null;
  if (current.kind === 'metadata') return '当前只有书目信息，不能关联为解读来源。';
  if (current.kind === 'abstract' ? sourceType !== 'abstract' : !fullTextTypes.has(sourceType)) return '材料类型必须与当前摘要或全文一致。';
  if (current.artifactId) return url && url !== current.url ? '来源地址与当前文件记录的网址不一致。' : null;
  return !current.url || url !== current.url ? '来源地址必须与当前论文文本的网址完全一致。' : null;
}
export function sourceBindingFileId(current: CurrentSource, active: boolean): string | undefined {
  return active ? current.artifactId || undefined : undefined;
}
type RightsDraft = { status: JournalRightsStatus; confidence: JournalSourceConfidence; statement: string; license: string; permissions: SourcePermissions; active: boolean };
function initialDraft(source?: JournalArticleSourceRecord): RightsDraft { return { status: source?.rightsStatus ?? 'unknown', confidence: source?.sourceConfidence ?? 'editor_claimed', statement: source?.evidence.statement || source?.notes || '', license: source?.evidence.license ?? '', permissions: source ? { ...source.permissions } : emptySourcePermissions(), active: source?.activeForGeneration ?? false }; }
function RightsFields({ value, onChange, disabled }: { value: RightsDraft; onChange: (value: RightsDraft) => void; disabled: boolean }) {
  const consent = HERMES_PERMISSIONS.every((key) => value.permissions[key]); const partial = !consent && HERMES_PERMISSIONS.some((key) => value.permissions[key]); const consentRef = React.useRef<HTMLInputElement>(null);
  React.useEffect(() => { if (consentRef.current) consentRef.current.indeterminate = partial; }, [partial]);
  const publicOptions: Array<[keyof SourcePermissions, string, string]> = [['publicDerivative', '公开文字解读', '生成结果经期刊审批后才会公开。'], ['figureReuse', '在公开内容中使用论文原图', '将原论文中的图片直接展示在公开解读或图卡中；仅供 AI 分析图片不属于此项。'], ['derivativeIllustration', '生成衍生示意图', '基于研究内容绘制新的解释性示意图，不冒充原图或实验数据。'], ['publicSource', '公开原始材料', '允许公开展示相应原始材料；不包含内部授权证明。']];
  return <fieldset disabled={disabled} className="grid min-w-0 gap-4 border-0 p-0"><div className="grid gap-4 sm:grid-cols-2">
    <label className="grid gap-2 text-sm">材料许可范围<select className={control} value={value.status} onChange={(event) => { const status = event.target.value as JournalRightsStatus; onChange({ ...value, status, permissions: limitPermissions(status, value.permissions) }); }}>{statuses.map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label className="grid gap-2 text-sm">核验状态<select className={control} value={value.confidence} onChange={(event) => onChange({ ...value, confidence: event.target.value as JournalSourceConfidence })}>{confidences.map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label className="grid gap-2 text-sm">许可名称<input className={control} value={value.license} placeholder="填写实际适用的许可或书面授权名称" onChange={(event) => onChange({ ...value, license: event.target.value })} /></label></div>
    <div className="border border-os-rule-paper p-4"><label className="flex items-start gap-3 text-sm"><input ref={consentRef} type="checkbox" checked={consent} disabled={!HERMES_PERMISSIONS.every((key) => STATUS_PERMISSIONS[value.status].includes(key))} onChange={(event) => onChange({ ...value, permissions: setHermesConsent(value.status, value.permissions, event.target.checked) })} /><span>Hermes 助手 AI 解读（用途授权）</span></label><p className="mb-0 mt-3 text-sm leading-6 text-os-muted-paper">请注意，{HERMES_DISCLOSURE}</p>{partial ? <p className="mt-2 text-xs text-os-muted-paper">历史记录包含部分处理权限，请按实际授权核对。未勾选不会自动补齐权限。</p> : null}</div>
    <div className="grid gap-4 sm:grid-cols-2">{publicOptions.map(([key, label, help]) => <label className="flex items-start gap-3 text-sm" key={key}><input type="checkbox" disabled={!STATUS_PERMISSIONS[value.status].includes(key)} checked={value.permissions[key]} onChange={(event) => onChange({ ...value, permissions: { ...value.permissions, [key]: event.target.checked } })} /><span>{label}<small className="mt-1 block leading-5 text-os-muted-paper">{help}</small></span></label>)}</div>
    <label className="grid gap-2 text-sm">授权从哪里获得？（必填）<textarea required rows={4} value={value.statement} placeholder={RIGHTS_EXAMPLE} className="border border-os-rule-paper bg-transparent p-3 placeholder:text-os-muted-paper" onChange={(event) => onChange({ ...value, statement: event.target.value })} /><span className="text-xs leading-6 text-os-muted-paper">请填写真实来源及允许的用途。填写声明不等于已核验，公开可访问也不等于允许加工或公开原图。</span></label><label className="flex gap-3 text-sm"><input type="checkbox" checked={value.active} onChange={(event) => onChange({ ...value, active: event.target.checked })} />将当前论文文本与此授权记录关联</label></fieldset>;
}
function Scope({ capability, busy, onRecalculate }: { capability: ArticleProcessingCapability; busy: boolean; onRecalculate?: () => void }) {
  const generated: Array<[string, boolean]> = [['书目信息', capability.canGenerateMetadataPage], ['摘要级解读', capability.canGenerateAbstractSummary], ['完整六字段', capability.canGenerateFullSixFields], ['图义说明', capability.canGenerateFigureExplanation], ['可复现性说明', capability.canGenerateReproducibilityField], ['衍生示意图', capability.canGenerateDerivativeIllustration]];
  const visible: Array<[string, boolean]> = [['文字摘要', capability.canPublishPublicSummary], ['完整解读', capability.canPublishFullInterpretation], ['论文图片', capability.canPublishFigures], ['公开 API', capability.canExposeViaApi]];
  return <section className="border border-os-rule-paper p-5" aria-labelledby="journal-scope-heading"><div className="flex flex-wrap items-center justify-between gap-4"><h2 id="journal-scope-heading" className="m-0 text-xl font-normal">加工与公开范围</h2>{onRecalculate ? <button className={control} disabled={busy} onClick={onRecalculate}>重新评估范围</button> : null}</div><div className="mt-4 grid gap-5 sm:grid-cols-2">{([['可生成', generated], ['可公开', visible]] as const).map(([title, entries]) => <div key={title}><h3 className="text-base font-normal">{title}</h3>{entries.map(([label, enabled]) => <p key={label} className="my-1 text-sm">{enabled ? '允许' : '不允许'}：{label}</p>)}</div>)}</div>{capability.limitations.length ? <p className="text-sm text-os-muted-paper">限制：{capability.limitations.join('；')}</p> : null}{capability.blockingReasons.length ? <p className="text-sm text-os-vermilion-ink">需要处理：{capability.blockingReasons.join('；')}</p> : null}<p className="mb-0 text-xs text-os-muted-paper">最近评估：{new Date(capability.lastEvaluatedAt).toLocaleString('zh-CN')}。允许公开仍需经过期刊审批。</p></section>;
}
function SourceCard({ source, busy, canEdit, onSave }: { source: JournalArticleSourceRecord; busy: boolean; canEdit: boolean; onSave: (source: JournalArticleSourceRecord, draft: RightsDraft) => Promise<boolean> }) {
  const [draft, setDraft] = React.useState(() => initialDraft(source)); const dirty = React.useRef(false);
  React.useEffect(() => { if (!dirty.current) setDraft(initialDraft(source)); }, [source]);
  return <details className="min-w-0 border border-os-rule-paper p-5"><summary className="cursor-pointer break-words">{source.title || sourceTypes.find(([key]) => key === source.sourceType)?.[1] || source.sourceType} · {statuses.find(([key]) => key === source.rightsStatus)?.[1]}</summary><form className="mt-5 grid gap-4" onSubmit={(event) => { event.preventDefault(); if (!canEdit) return; dirty.current = false; void onSave(source, draft).then((saved) => { if (!saved) dirty.current = true; }); }}><RightsFields value={draft} onChange={(value) => { dirty.current = true; setDraft(value); }} disabled={busy || !canEdit} />{source.evidence.expiresAt ? <p className="text-xs text-os-muted-paper">历史授权记录有效至：{new Date(source.evidence.expiresAt).toLocaleString('zh-CN')}；本表单不会修改该记录。</p> : null}{canEdit ? <button type="submit" className={`${control} justify-self-start`} disabled={busy}>保存授权记录</button> : null}</form></details>;
}
export function JournalSourceRightsMatrix({ journalId, articleId }: { journalId: string; articleId: string }) {
  const [sources, setSources] = React.useState<JournalArticleSourceRecord[]>([]); const [history, setHistory] = React.useState<JournalSourceHistoryEntry[]>([]);
  const [capability, setCapability] = React.useState<ArticleProcessingCapability | null>(null); const [revision, setRevision] = React.useState<number | null>(null); const [title, setTitle] = React.useState(''); const [currentSource, setCurrentSource] = React.useState<CurrentSource>({ kind: 'metadata', url: '', label: '' }); const [canEdit, setCanEdit] = React.useState(false);
  const [error, setError] = React.useState(''); const [message, setMessage] = React.useState(''); const [busy, setBusy] = React.useState(false); const inFlight = React.useRef(false); const generation = React.useRef(0);
  const [draft, setDraft] = React.useState<RightsDraft>(() => initialDraft()); const [sourceType, setSourceType] = React.useState<JournalSourceType>('abstract'); const [sourceTitle, setSourceTitle] = React.useState(''); const [url, setUrl] = React.useState('');
  const load = React.useCallback(async (): Promise<boolean> => {
    const request = ++generation.current;
    try { const [matrix, article, dashboard] = await Promise.all([getJournalArticleSources(journalId, articleId), getJournalArticle(journalId, articleId), getJournalDashboard(journalId)]); if (request !== generation.current) return false;
      setSources(matrix.sources); setHistory(matrix.history); setCapability(matrix.capability); setRevision(matrix.articleRevision); setTitle(article.article.metadata.title); setCurrentSource(article.article.source as CurrentSource); setCanEdit(['owner', 'admin', 'editor'].includes(dashboard.membership.role)); setError(''); return true;
    } catch (cause) { if (request === generation.current) { setCanEdit(false); setError(cause instanceof Error ? cause.message : '无法加载授权记录。'); if (cause instanceof ApiClientError && [401, 403, 404].includes(cause.status)) { setCapability(null); setSources([]); setHistory([]); } } return false; }
  }, [journalId, articleId]);
  React.useEffect(() => { void load(); return () => { generation.current += 1; }; }, [load]);
  async function mutate(action: () => Promise<unknown>, success = '记录已保存并重新评估；未运行 AI，也未公开材料。'): Promise<boolean> {
    if (inFlight.current || revision === null || !canEdit) return false; inFlight.current = true; setBusy(true); setMessage('');
    try { await action(); const fresh = await load(); setMessage(fresh ? success : '操作已提交，但刷新失败，请重新加载后继续。'); return fresh; }
    catch (cause) { setMessage(cause instanceof Error ? cause.message : '操作失败，请刷新重试。'); return false; } finally { inFlight.current = false; setBusy(false); }
  }
  function save(source: JournalArticleSourceRecord, value: RightsDraft) { return mutate(() => updateJournalArticleSourceRights(journalId, articleId, source.id, { revision: revision!, rightsStatus: value.status, sourceConfidence: value.confidence, permissions: limitPermissions(value.status, value.permissions), evidence: editSourceEvidence(source.evidence, value.statement, value.license), notes: value.statement.trim(), activeForGeneration: value.active })); }
  if (error && !capability) return <section role="alert"><p>{error}</p><button className={control} onClick={() => void load()}>重新加载授权记录</button></section>;
  if (!capability) return <p role="status">正在加载来源与授权记录…</p>;
  return <div className="grid min-w-0 gap-7"><header className="border-b border-os-rule-paper pb-5"><Link href={`/journals/manage/${journalId}/articles/${articleId}`} className="text-sm">← 返回论文工作台</Link><h1 className="mt-5 break-words text-3xl font-normal">{title}</h1><p className="text-sm text-os-muted-paper">材料授权与公开范围。保存许可不会启动解读，也不会自动发布。</p></header>{error ? <div role="alert"><p>{error} 请重新加载后继续。</p><button className={control} onClick={() => void load()}>重新加载</button></div> : null}
    <Scope capability={capability} busy={busy} onRecalculate={canEdit ? () => { void mutate(() => recalculateJournalProcessingCapability(journalId, articleId, { revision: revision! }), '范围已重新评估；未运行 AI，也未公开材料。'); } : undefined} />
    <section className="grid gap-4" aria-labelledby="journal-material-rights"><h2 id="journal-material-rights" className="m-0 text-xl font-normal">材料与授权记录</h2>{!sources.length ? <p className="text-sm text-os-muted-paper">尚未登记独立材料授权。</p> : sources.map((source) => <SourceCard key={source.id} source={source} busy={busy} canEdit={canEdit} onSave={save} />)}</section>
    {canEdit ? <details className="border-t border-os-rule-paper pt-5"><summary className="cursor-pointer text-lg">登记来源与授权依据</summary><p className="text-sm text-os-muted-paper">此处登记已有材料的来源和授权，不是文件上传入口。授权证明应保持内部可见。</p><p className="break-words text-sm text-os-muted-paper">当前论文文本：{currentSource.label || (currentSource.kind === 'fulltext' ? '全文' : currentSource.kind === 'abstract' ? '摘要' : '书目信息')}。{currentSource.artifactId ? `关联上传文件 ${currentSource.artifactId}` : currentSource.url ? `关联网址 ${currentSource.url}` : '尚无可关联的文件或网址'}。勾选关联时，材料类型须与当前文本一致；网址来源须填写完全相同的网址。</p><form className="mt-5 grid gap-4" onSubmit={(event) => { event.preventDefault(); const sourceUrl = url.trim(); const issue = sourceBindingIssue(currentSource, sourceType, sourceUrl, draft.active); if (issue) { setMessage(issue); return; } void mutate(() => addJournalArticleSource(journalId, articleId, { revision: revision!, source: { sourceType, title: sourceTitle.trim() || undefined, url: sourceUrl || undefined, fileId: sourceBindingFileId(currentSource, draft.active), rightsStatus: draft.status, sourceConfidence: draft.confidence, permissions: limitPermissions(draft.status, draft.permissions), evidence: editSourceEvidence({ statement: '' }, draft.statement, draft.license), notes: draft.statement.trim(), activeForGeneration: draft.active } })).then((saved) => { if (saved) { setDraft(initialDraft()); setSourceTitle(''); setUrl(''); } }); }}><fieldset disabled={busy} className="grid min-w-0 gap-4 border-0 p-0 sm:grid-cols-2"><label className="grid gap-2 text-sm">材料类型<select className={control} value={sourceType} onChange={(event) => setSourceType(event.target.value as JournalSourceType)}>{sourceTypes.map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label className="grid gap-2 text-sm">材料名称<input className={control} value={sourceTitle} onChange={(event) => setSourceTitle(event.target.value)} /></label><label className="grid gap-2 text-sm sm:col-span-2">来源地址<input type="url" className={control} value={url} placeholder="https://…" onChange={(event) => setUrl(event.target.value)} /></label></fieldset><RightsFields value={draft} onChange={(value) => { if (value.active && !draft.active && !currentSource.artifactId && !url.trim()) setUrl(currentSource.url); setDraft(value); }} disabled={busy} />{sourceBindingIssue(currentSource, sourceType, url.trim(), draft.active) ? <p role="alert" className="text-sm text-os-vermilion-ink">{sourceBindingIssue(currentSource, sourceType, url.trim(), draft.active)}</p> : null}<button type="submit" className={`${control} justify-self-start`} disabled={busy || !!sourceBindingIssue(currentSource, sourceType, url.trim(), draft.active)}>保存来源与授权</button></form></details> : null}
    <details className="border-t border-os-rule-paper pt-5"><summary className="cursor-pointer text-lg">授权变更记录</summary>{history.length ? history.map((entry) => <div className="border-b border-os-rule-paper py-3 text-sm" key={entry.id}><p>{entry.action === 'journal.source.add' ? '登记来源与授权' : '更新授权'} · {new Date(entry.createdAt).toLocaleString('zh-CN')}</p>{entry.actorId ? <p className="text-xs text-os-muted-paper">操作者：{entry.actorId}</p> : null}</div>) : <p className="text-sm text-os-muted-paper">暂无变更记录。</p>}</details>{busy || message ? <p role="status">{busy ? '正在保存并评估…' : message}</p> : null}
  </div>;
}
