'use client';
import * as React from 'react';
import { addJournalMember, activateJournal, listJournalMembers, removeJournalMember, updateJournalHomepage, updateJournalMember, type JournalMember, type JournalSummary } from '@/lib/journal-api';

/** @deprecated The routed management page uses JournalManagementWorkbench and its governance section. */
export function JournalSettings({ journal, role, onChanged }: { journal: JournalSummary; role: string; onChanged: () => Promise<void> }) {
  const [members, setMembers] = React.useState<JournalMember[]>([]); const [email, setEmail] = React.useState(''); const [message, setMessage] = React.useState(''); const [description, setDescription] = React.useState(journal.description ?? ''); const canManage = role === 'owner' || role === 'admin';
  const load = React.useCallback(() => listJournalMembers(journal.id).then((r) => setMembers(r.items)).catch((e) => setMessage(e instanceof Error ? e.message : '无法加载成员')), [journal.id]); React.useEffect(() => { if (canManage) void load(); }, [canManage, load]);
  const saveHome = async () => { try { await updateJournalHomepage(journal.id, { revision: journal.revision ?? 0, description }); await onChanged(); setMessage('期刊主页预览已更新。'); } catch (e) { setMessage(e instanceof Error ? e.message : '无法保存主页'); } };
  if (!canManage) return null;
  return <section className="border-t border-os-rule-paper pt-6"><h2 className="text-xl font-normal">主页与成员</h2><label className="mt-3 grid gap-2 text-sm">期刊简介<textarea rows={3} value={description} onChange={(e) => setDescription(e.target.value)} className="border border-os-rule-paper bg-transparent p-3" /></label><div className="mt-3 flex flex-wrap gap-2"><button className="border border-os-rule-paper px-3 py-2 text-sm" onClick={() => void saveHome()}>保存主页预览</button>{!journal.homepagePublished && journal.status === 'active' ? <button className="border border-os-rule-paper px-3 py-2 text-sm" onClick={() => void activateJournal(journal.id).then(onChanged).catch((e) => setMessage(e.message))}>激活期刊主页</button> : null}</div><div className="mt-7"><h3 className="text-lg font-normal">成员</h3><div className="flex gap-2"><input value={email} onChange={(e) => setEmail(e.target.value)} placeholder="受邀成员邮箱" className="min-h-10 border border-os-rule-paper px-3" /><button className="border border-os-rule-paper px-3 text-sm" onClick={() => void addJournalMember(journal.id, { email, role: 'editor' }).then(() => { setEmail(''); return load(); }).catch((e) => setMessage(e.message))}>添加编辑</button></div><div className="mt-3 divide-y divide-os-rule-paper">{members.map((member) => <div className="flex flex-wrap items-center gap-2 py-3" key={member.userId}><span className="min-w-40 text-sm">{member.displayName || member.email}</span><select value={member.role} disabled={member.role === 'owner'} onChange={(e) => void updateJournalMember(journal.id, member.userId, e.target.value as 'admin' | 'editor' | 'reviewer').then(load).catch((e) => setMessage(e instanceof Error ? e.message : '操作失败'))} className="border border-os-rule-paper bg-transparent p-1 text-sm"><option value="admin">管理员</option><option value="editor">编辑</option><option value="reviewer">审核者</option><option value="owner">负责人</option></select>{member.role !== 'owner' ? <button className="text-sm text-os-vermilion-ink" onClick={() => void removeJournalMember(journal.id, member.userId).then(load)}>移除</button> : null}</div>)}</div></div>{message ? <p role="status" className="mt-3 text-sm">{message}</p> : null}</section>;
}
