import { createHash } from 'node:crypto';
import { constants } from 'node:fs';
import { lstat, mkdir, open, rename, rm } from 'node:fs/promises';
import { dirname, isAbsolute, join, parse } from 'node:path';
import type { StoryboardDocument, StoryboardView, VideoSceneDirection } from '@openscience/domain';
import type { HostVideoInput } from './host-video-spool';

const MAX_JSON = 512 * 1024; const MAX_PNG = 10 * 1024 * 1024; const MAX_MP4 = 256 * 1024 * 1024;
const MAX_DEADLINE = 30 * 60_000; const READY_MAX_AGE = 60_000; const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export interface SynclipVideoSpoolConfig { inboxDir: string; resultsDir: string; timeoutMs?: number; pollIntervalMs?: number; now?: () => number; sleep?: (milliseconds: number) => Promise<void>; withSubmission?: <T>(owner: { taskId: string; executionAttempt?: number }, publish: () => Promise<T>) => Promise<T>; }
export interface SynclipVideoInput { taskId: string; executionAttempt: number; profile: 'content-driven-v1'; sourceClaimIds: string[]; storyboard: StoryboardDocument; locale?: StoryboardView['locale']; style?: StoryboardView['style']; sceneImages: Buffer[]; sceneImageTaskIds?: string[]; }
export interface SynclipVideoResult { filePath: string; size: number; contentHash: string; contentType: 'video/mp4'; generator: 'Synclip commercial video'; generatorVersion: 'ltx23'; inputHash: string; narration: { provider: 'synclip-audio-pending'; speaker: 'none'; timingStatus: 'not_available' }; metrics: Record<string, unknown>; runtime: { provider: 'synclip'; model: 'ltx23'; adapterRevision: string }; }
function fail(message = 'INVALID_SYNCLIP_VIDEO_SPOOL_OUTPUT'): never { throw new Error(message); }
async function directory(path: string): Promise<void> { if (!isAbsolute(path)) fail(); let current = path; for (;;) { const info = await lstat(current); if (!info.isDirectory() || info.isSymbolicLink()) fail(); if (current === parse(current).root) return; current = dirname(current); } }
async function boundedRead(path: string, maximum: number): Promise<Buffer> { const before = await lstat(path); if (!before.isFile() || before.isSymbolicLink() || before.size <= 0 || before.size > maximum) fail(); const file = await open(path, constants.O_RDONLY | (constants.O_NOFOLLOW ?? 0)); try { const after = await file.stat(); if (!after.isFile() || after.ino !== before.ino || after.dev !== before.dev || after.size !== before.size) fail(); return await file.readFile(); } finally { await file.close(); } }
async function exclusiveWrite(path: string, bytes: Buffer): Promise<void> { const file = await open(path, constants.O_WRONLY | constants.O_CREAT | constants.O_EXCL | (constants.O_NOFOLLOW ?? 0), 0o600); try { await file.writeFile(bytes); await file.sync(); } finally { await file.close(); } }
function durationForScene(value: number): 5 | 10 | 15 { return value <= 7 ? 5 : value <= 12 ? 10 : 15; }
function directionText(direction: VideoSceneDirection | undefined): string { if (!direction) throw new Error('VIDEO_DIRECTION_REQUIRED'); const exclusions = direction.negativeConstraints.length ? ' Do not: ' + direction.negativeConstraints.join('; ') + '.' : ''; return 'Shot type: ' + direction.shotType + '. Purpose: ' + direction.purpose + '. Locked subject: ' + direction.subjectLock + '. Generated elements: ' + direction.generatedElements + '. Motion: ' + direction.motion + '. Camera: ' + direction.camera + '.' + exclusions; }
function compileShotPrompt(storyboard: StoryboardDocument, scene: StoryboardDocument['scenes'][number], locale: string): string { if (!storyboard.videoProduction || storyboard.videoProduction.modelPolicy !== 'commercial-primary') throw new Error('COMMERCIAL_VIDEO_PLAN_REQUIRED'); return ['Scientific explainer shot. Preserve approved subject identity, geometry, direction, and causal relationship exactly.', 'Locale: ' + locale + '. Global continuity bible: ' + storyboard.videoProduction.visualContinuity, 'Scene: ' + scene.title + '. Reader-facing narration context: ' + scene.narration, 'Approved visual action: ' + scene.visualAction, directionText(scene.videoDirection), 'Use smooth physically plausible motion, restrained cinematic lighting, and clean scientific composition. Do not render subtitles, formulas, logos, watermarks, or invented labels. Do not change scientific meaning. Spoken narration is external; use only subtle non-verbal ambience if supplied.'].join('\n'); }
export class SynclipVideoSpool {
  private readonly now: () => number; private readonly sleep: (milliseconds: number) => Promise<void>; private readonly timeout: number;
  constructor(private readonly config: SynclipVideoSpoolConfig) { if (!isAbsolute(config.inboxDir) || !isAbsolute(config.resultsDir) || config.inboxDir === config.resultsDir) fail(); this.timeout = config.timeoutMs ?? MAX_DEADLINE; if (!Number.isSafeInteger(this.timeout) || this.timeout < 1 || this.timeout > MAX_DEADLINE || (config.pollIntervalMs !== undefined && (!Number.isSafeInteger(config.pollIntervalMs) || config.pollIntervalMs < 1 || config.pollIntervalMs > 60_000))) fail(); this.now = config.now ?? Date.now; this.sleep = config.sleep ?? (ms => new Promise(resolve => setTimeout(resolve, ms))); }
  async generate(input: SynclipVideoInput | HostVideoInput): Promise<SynclipVideoResult> {
    await directory(this.config.inboxDir); await directory(this.config.resultsDir);
    const readyPath = join(this.config.resultsDir, '.ready'); const ready = JSON.parse((await boundedRead(readyPath, MAX_JSON)).toString()) as Record<string, unknown>; const readyStat = await lstat(readyPath);
    if (ready.schemaVersion !== 1 || ready.provider !== 'synclip' || ready.accepting !== true || ready.model !== 'ltx23' || typeof ready.updatedAt !== 'number' || this.now() - ready.updatedAt > READY_MAX_AGE || readyStat.mtimeMs < this.now() - READY_MAX_AGE) fail('SYNCLIP_VIDEO_UNAVAILABLE');
    if (input.profile !== 'content-driven-v1' || !UUID.test(input.taskId) || !Number.isInteger(input.executionAttempt) || input.executionAttempt < 1 || input.sourceClaimIds.length < 1 || input.sourceClaimIds.length > 12 || input.sceneImages.length !== input.storyboard.scenes.length || input.storyboard.scenes.length < 3 || input.storyboard.scenes.length > 6) fail('INVALID_VIDEO_INPUT');
    input.sceneImages.forEach(bytes => { if (bytes.length < 33 || bytes.length > MAX_PNG || bytes.subarray(0, 8).toString('hex') !== '89504e470d0a1a0a') fail('INVALID_VIDEO_INPUT'); });
    if (!input.sceneImageTaskIds || input.sceneImageTaskIds.length !== input.sceneImages.length
      || input.sceneImageTaskIds.some(id => !UUID.test(id))) fail('SYNCLIP_VIDEO_IMAGE_RECEIPTS_REQUIRED');
    const locale = input.locale ?? 'zh'; const style = input.style ?? 'scientific';
    const scenes = input.storyboard.scenes.map((scene, index) => ({ index, title: scene.title, narration: scene.narration, sourceClaimIds: scene.sourceClaimIds, durationSeconds: durationForScene(scene.durationSeconds ?? 5), prompt: compileShotPrompt(input.storyboard, scene, locale), image: { name: 'scene-' + index + '.png', size: input.sceneImages[index]!.length, sha256: createHash('sha256').update(input.sceneImages[index]!).digest('hex'), requestId: input.sceneImageTaskIds![index]! } }));
    const storyboardBytes = Buffer.from(JSON.stringify({ ...input.storyboard, locale, style })); if (storyboardBytes.length > MAX_JSON) fail('INVALID_VIDEO_INPUT');
    const files = { storyboard: { name: 'storyboard.json', size: storyboardBytes.length, sha256: createHash('sha256').update(storyboardBytes).digest('hex') }, scenes: scenes.map(scene => scene.image) }; const inputHash = createHash('sha256').update(JSON.stringify(files)).digest('hex');
    const request = { schemaVersion: 1, id: input.taskId, taskId: input.taskId, executionAttempt: input.executionAttempt, profile: input.profile, sourceClaimIds: input.sourceClaimIds, inputHash, createdAt: this.now(), deadlineAt: this.now() + this.timeout, provider: 'synclip', model: 'ltx23', resolution: '720p', files, scenes };
    const stage = join(this.config.inboxDir, '.' + input.taskId + '.' + Math.random().toString(36).slice(2) + '.tmp'); const target = join(this.config.inboxDir, input.taskId);
    const submit = async () => { await mkdir(stage, { mode: 0o700 }); try { await exclusiveWrite(join(stage, 'storyboard.json'), storyboardBytes); for (const [index, bytes] of input.sceneImages.entries()) await exclusiveWrite(join(stage, 'scene-' + index + '.png'), bytes); await exclusiveWrite(join(stage, 'request.json'), Buffer.from(JSON.stringify(request))); try { await rename(stage, target); } catch (error) { if ((error as NodeJS.ErrnoException).code !== 'EEXIST' && (error as NodeJS.ErrnoException).code !== 'ENOTEMPTY') throw error; const existing = JSON.parse((await boundedRead(join(target, 'request.json'), MAX_JSON)).toString()) as Record<string, unknown>; if (existing.inputHash !== inputHash || existing.taskId !== input.taskId || existing.executionAttempt !== input.executionAttempt) fail('UNCERTAIN'); } } finally { await rm(stage, { recursive: true, force: true }).catch(() => undefined); } };
    if (this.config.withSubmission) await this.config.withSubmission({ taskId: input.taskId, executionAttempt: input.executionAttempt }, submit); else await submit();
    const resultDir = join(this.config.resultsDir, input.taskId);
    while (this.now() < request.deadlineAt) { try { await directory(resultDir); const result = JSON.parse((await boundedRead(join(resultDir, 'result.json'), MAX_JSON)).toString()) as Record<string, unknown>; if (result.schemaVersion !== 1 || result.id !== input.taskId || result.inputHash !== inputHash || result.executionAttempt !== input.executionAttempt) fail('UNCERTAIN'); if (result.status !== 'succeeded') throw new Error(result.status === 'uncertain' ? 'UNCERTAIN' : 'SYNCLIP_VIDEO_EXECUTION_FAILED'); if (result.contentType !== 'video/mp4' || typeof result.outputSha256 !== 'string' || !/^[a-f0-9]{64}$/u.test(result.outputSha256) || !Number.isSafeInteger(result.outputSize) || Number(result.outputSize) <= 0 || Number(result.outputSize) > MAX_MP4) fail(); const filePath = join(resultDir, 'result.mp4'); const bytes = await boundedRead(filePath, MAX_MP4); const hash = createHash('sha256').update(bytes).digest('hex'); if (hash !== result.outputSha256 || bytes.length !== result.outputSize || !bytes.subarray(4, 12).includes(Buffer.from('ftyp'))) fail(); const metrics = JSON.parse((await boundedRead(join(resultDir, 'metrics.json'), MAX_JSON)).toString()) as Record<string, unknown>; return { filePath, size: bytes.length, contentHash: hash, contentType: 'video/mp4', generator: 'Synclip commercial video', generatorVersion: 'ltx23', inputHash, narration: { provider: 'synclip-audio-pending', speaker: 'none', timingStatus: 'not_available' }, metrics, runtime: { provider: 'synclip', model: 'ltx23', adapterRevision: String(result.adapterRevision ?? 'synclip-video-v1') } }; } catch (error) { if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error; } await this.sleep(Math.min(this.config.pollIntervalMs ?? 1000, request.deadlineAt - this.now())); }
    throw new Error('EXPIRED');
  }
}
