export const academicProfileCopy = {
  zh: {
    pageTitle: '个人学术主页', purpose: '汇集你的研究与贡献，用一个链接介绍自己。',
    uses: ['申请职位、博士后与访问机会；', '寻找研究合作，寻找产业界合作；', '招生与招聘；', '成果传播；'],
    works: '代表工作与贡献', interests: '当前关注与交流', more: '更多了解我',
    bio: '简介', contact: '联系方式', email: '查看邮箱', share: '分享主页', copied: '链接已复制', copyFailed: '复制失败，请手动复制地址',
    role: '本人角色与贡献', detail: '详情', problem: '想解决什么问题', process: '工作过程', related: '相关材料',
    cv: '个人简历', lab: '课题组主页', education: '求学经历', addable: '可添加报告、访谈、新闻稿、视频等内容的链接。',
    published: '已公开论文', emptyPublications: '暂无已公开论文', close: '关闭',
    manage: '管理我的学术主页', editor: '编辑学术主页', draft: '保存草稿', publish: '发布当前草稿', unpublish: '取消公开',
    preview: '查看公开主页', unpublished: '尚未公开', publishedState: '已公开', saving: '正在保存…', saved: '草稿已保存',
    publishedMessage: '主页已公开', unpublishedMessage: '主页已取消公开', conflict: '资料已在其他页面更新，请重新加载后再保存。',
    loading: '正在加载学术主页…', unavailable: '此学术主页尚未公开。', loadError: '暂时无法加载学术主页，请重试。', retry: '重试', discardReload: '放弃本地修改并重新加载',
    identity: '个人资料', avatar: '头像（PNG、JPEG、WebP，最多 256 KB）', name: '姓名', englishName: '英文姓名', title: '职务', institution: '单位', labName: '实验室', contactEmail: '公开联系邮箱（选填；访客点击后显示）', orcid: 'ORCID 链接', scholar: 'Google Scholar 链接',
    workCategory: '类别', period: '时间', shortTitle: '首页短标题', summary: '首页贡献短文', fullTitle: '详情完整标题', workProblem: '问题', contribution: '完整个人贡献', workProcess: '工作过程', links: '相关材料', linkLabel: '链接名称', linkUrl: '原始地址（https://…）',
    addWork: '添加代表工作', addInterest: '添加交流方向', addLink: '添加链接', addMaterial: '添加材料', addEducation: '添加经历', remove: '删除', interestTitle: '标题', interestBody: '说明', cvUrl: '个人简历地址', labUrl: '课题组主页地址', educationTitle: '经历名称', educationDetails: '经历说明', educationUrl: '相关地址（选填）',
    saveFirst: '请先保存草稿，再发布。', privateHint: '草稿仅自己可见；点击发布后，当前保存的内容才会公开。', emptyHint: '从姓名和一段简介开始填写；未填写的内容不会向访客显示。', invalidUrl: '请填写有效的 http 或 https 地址。', invalidEmail: '请检查公开联系邮箱格式。', requiredField: '请填写', invalidAvatar: '请选择不超过 256 KB 的 PNG、JPEG 或 WebP 图片。',
  },
  en: {
    pageTitle: 'Academic profile', purpose: 'Bring together your research and contributions, and introduce yourself with one link.',
    uses: ['Applications for positions, postdocs, and visits;', 'Research and industry collaboration;', 'Student recruitment and hiring;', 'Sharing research outcomes;'],
    works: 'Selected work and contributions', interests: 'Current interests and conversations', more: 'More about me',
    bio: 'About', contact: 'Contact', email: 'Show email', share: 'Share profile', copied: 'Link copied', copyFailed: 'Could not copy; please copy the address manually',
    role: 'My role and contribution', detail: 'Details', problem: 'Problem addressed', process: 'Process', related: 'Related materials',
    cv: 'CV', lab: 'Lab website', education: 'Education', addable: 'Add links to talks, interviews, news, videos, and more.',
    published: 'Published papers', emptyPublications: 'No published papers yet', close: 'Close',
    manage: 'Manage my academic profile', editor: 'Edit academic profile', draft: 'Save draft', publish: 'Publish saved draft', unpublish: 'Unpublish',
    preview: 'View public profile', unpublished: 'Not published', publishedState: 'Published', saving: 'Saving…', saved: 'Draft saved',
    publishedMessage: 'Profile published', unpublishedMessage: 'Profile unpublished', conflict: 'This profile changed in another window. Reload before saving.',
    loading: 'Loading academic profile…', unavailable: 'This academic profile is not published.', loadError: 'Could not load this academic profile. Please retry.', retry: 'Retry', discardReload: 'Discard local edits and reload',
    identity: 'Identity', avatar: 'Portrait (PNG, JPEG, WebP, up to 256 KB)', name: 'Name', englishName: 'English name', title: 'Position', institution: 'Institution', labName: 'Lab', contactEmail: 'Public contact email (optional; shown on click)', orcid: 'ORCID link', scholar: 'Google Scholar link',
    workCategory: 'Category', period: 'Period', shortTitle: 'Short title', summary: 'Short contribution summary', fullTitle: 'Full title', workProblem: 'Problem', contribution: 'Full personal contribution', workProcess: 'Process', links: 'Related materials', linkLabel: 'Link label', linkUrl: 'Original URL (https://…)',
    addWork: 'Add work', addInterest: 'Add interest', addLink: 'Add link', addMaterial: 'Add material', addEducation: 'Add education', remove: 'Remove', interestTitle: 'Title', interestBody: 'Description', cvUrl: 'CV URL', labUrl: 'Lab URL', educationTitle: 'Education title', educationDetails: 'Details', educationUrl: 'Related URL (optional)',
    saveFirst: 'Save the draft before publishing.', privateHint: 'Only you can see drafts. Publishing makes the current saved content public.', emptyHint: 'Start with your name and a short bio. Empty sections stay hidden from visitors.', invalidUrl: 'Enter a valid http or https URL.', invalidEmail: 'Check the public contact email.', requiredField: 'Please fill in', invalidAvatar: 'Choose a PNG, JPEG, or WebP image under 256 KB.',
  },
} as const;
