export function guideWorkspaceCopy(locale: string) {
  return locale === 'en' ? {
    heading: 'Develop your research with Hermes', placeholder: 'Upload a paper, or tell Hermes what you want to do.',
    upload: 'Upload a paper', direct: 'Fill in directly', send: 'Send',
    prompts: ['Help me identify this paper’s core contribution.', 'Organize the paper into structured research.', 'Help me check whether this passage is clear.'],
    title: 'Research title', titlePlaceholder: 'A working title', workspaces: 'Personal workspace',
    signIn: 'Sign in to save and continue', required: 'Enter an idea or choose a file to begin.',
    saving: 'Saving…', saved: 'Private draft saved', retry: 'Retry', source: 'Source materials',
    research: 'Current research', newResearch: 'New research', update: 'Update a research version',
    updateDescription: 'Need to add to or revise an existing study? Choose it here, keep refining its content, and preserve the version history.',
    version: 'Version', noResearch: 'No research yet. Start above.', choose: 'Choose research',
    editor: 'Six dimensions', save: 'Save private draft', commit: 'Create a new private version',
    pending: 'Processing material', review: 'Review Hermes extraction', refresh: 'Refresh analysis',
    accept: 'Confirm these six fields', extractionUnavailable: 'The source analysis is still in progress or needs attention.',
    publish: 'Review and publish this version', published: 'The published version is preserved. Changes here become a new private version.',
    local: 'Sign in to submit. Your text is not stored with another account.',
    saveBeforeVersion: 'Save the private draft before creating a version.',
    switchWarning: 'Save your draft before switching research.', failure: 'The action failed. Retry without creating a duplicate.',
  } : {
    heading: '与 Hermes 一起完善研究', placeholder: '上传论文，或告诉 Hermes 你想完成什么。',
    upload: '上传论文', direct: '直接填写', send: '发送',
    prompts: ['帮我梳理这篇论文的核心贡献。', '将论文内容整理成结构化研究。', '帮我检查这段表述是否清楚。'],
    title: '研究标题', titlePlaceholder: '先写一个暂定标题', workspaces: '个人工作空间',
    signIn: '登录后保存并继续', required: '请先写下想法或选择文件。',
    saving: '正在保存…', saved: '私有草稿已保存', retry: '重试', source: '来源材料',
    research: '当前研究', newResearch: '新建研究', update: '更新研究版本',
    updateDescription: '已有研究需要补充或修订？选择一项研究，继续完善内容并保留历史版本。',
    version: '版本', noResearch: '还没有研究，请从上方开始。', choose: '选择研究',
    editor: '六维研究内容', save: '保存私有草稿', commit: '创建新的私有版本',
    pending: '正在处理材料', review: '核对 Hermes 凝练结果', refresh: '刷新分析结果',
    accept: '确认这六个字段', extractionUnavailable: '来源分析仍在进行中，或需要进一步处理。',
    publish: '审核并发布此版本', published: '已公开的原版本会保留；这里的修改将成为新的私有版本。',
    local: '登录后可提交；当前文字不会带入其他账号。',
    saveBeforeVersion: '请先保存私有草稿，再创建研究版本。',
    switchWarning: '切换研究前请先保存草稿。', failure: '操作失败；重试会沿用本次请求，不会重复创建。',
  };
}
