import { apiRequest, prepareProtectedXhr } from './api';

export type JournalRole = 'owner' | 'admin' | 'editor' | 'reviewer';
export type JournalArticleState = 'draft' | 'needs_source' | 'processing' | 'review' | 'published' | 'corrected' | 'retracted';

export interface JournalSummary { id: string; slug: string; nameZh?: string | null; nameEn?: string | null; description?: string | null; logoUrl?: string | null; subjects: string[]; pIssn?: string | null; eIssn?: string | null; websiteUrl?: string | null; publisherName?: string | null; sponsorName?: string | null; publicArticleCount: number; homepagePublished: boolean; status: string; revision?: number; }
export interface JournalArticle { id: string; journalId: string; researchObjectId: string | null; workId: string; metadata: { title: string; doi?: string | null; authors: string[]; publishedDate?: string | null; journalTitle?: string | null; issns: string[]; originalUrl: string; abstract?: string | null }; directoryVisible: boolean; contentState: 'active' | 'restricted' | 'withdrawn'; revision: number; source: { kind: 'metadata' | 'abstract' | 'fulltext'; text: string; url: string; label: string; materials?: JournalArticleSourceRecord[] }; rights: ArticleRights; draft: JournalDraft | null; reviewState: 'draft' | 'submitted' | 'approved' | 'changes_requested'; reviewedRevision: number | null; reviewNote?: string | null; releases: Array<{ versionNo: number; publicId: string; url: string; publishedAt: string }>; jobs: Array<{ id: string; kind?: string; state?: string; status?: string; createdAt?: string; comparisonDraft?: unknown }> }
export interface PublicJournalArticle { id: string; contentState: 'active' | 'restricted' | 'withdrawn'; metadata: Pick<JournalArticle['metadata'], 'title' | 'doi' | 'authors' | 'publishedDate' | 'originalUrl'>; interpretationKind: 'abstract' | 'fulltext' | null; releases: Array<{ versionNo: number; publicId: string; url: string; publishedAt: string }>; }
export interface JournalPublic extends JournalSummary { publisherName?: string | null; sponsorName?: string | null; verifiedAt?: string | null; articles?: PublicJournalArticle[]; about?: string | null; }
export interface JournalApplicationInput { nameZh?: string; nameEn: string; pIssn?: string; eIssn?: string; websiteUrl: string; publisherName: string; sponsorName?: string; subjects: string[]; description: string; logoUrl?: string; applicantName: string; applicantTitle: string; applicantEmail: string; representationEvidence: string; plannedArticleCount: number; requestedServices: string[]; rightsDeclaration: string; rightsDeclarationVersion: string; }
export interface JournalApplication extends Partial<JournalApplicationInput> { id: string; revision: number; status: 'draft' | 'submitted' | 'needs_information' | 'approved' | 'rejected'; reviewReason?: string | null; submittedAt?: string | null; createdAt: string; updatedAt: string; journalId?: string | null; }
export interface ArticleRights { internalProcessing: boolean; derivativeGeneration: boolean; publicSource: boolean; publicDerivative: boolean; externalProcessing: boolean; license: string; evidence: string; }
export interface JournalDraft { summary: string; core: { problem: string; insight: string; method: string; results: string; limitations: string; reproducibility: string }; claims: Array<{ text: string; kind: 'experimental' | 'simulation' | 'theoretical' | 'review' | 'other'; evidence: { quote: string; locator: string } }>; figures: Array<{ label: string; purpose: string; finding: string; evidence: { quote: string; locator: string } }>; faq: Array<{ question: string; answer: string; evidence: { quote: string; locator: string } }>; scope: 'abstract' | 'fulltext'; language: 'zh' | 'en'; }
export interface JournalDashboard { journal: JournalSummary; articles: JournalArticle[]; grants: Array<{ id: string; amount: number; remaining: number; reserved: number; consumed: number; expiresAt: string | null }>; jobs: Array<{ id: string; state: string; articleId?: string }>; serviceRequests: JournalServiceRequest[]; stats: { published: number | null; articles: number; jobsSucceeded: number; pageViews: number | null; apiReads: number | null }; membership: { role: JournalRole }; }
export interface JournalServiceRequest { id: string; journalId?: string; annualVolume: number; language: string; figureScale: string; services: string[]; notes?: string | null; status: 'submitted' | 'quoted' | 'approved' | 'rejected' | 'cancelled'; reviewNotes?: string | null; trialAvailable?: boolean; createdAt: string; }
export type JournalSourceType = 'doi_metadata' | 'abstract' | 'public_full_text' | 'publisher_full_text' | 'editor_uploaded_pdf' | 'author_material' | 'supplementary' | 'figure_asset' | 'parsed_text' | 'ocr_visual_sidecar' | 'manual_note';
export type JournalRightsStatus = 'unknown' | 'metadata_only_allowed' | 'abstract_processing_allowed' | 'internal_processing_only' | 'public_summary_allowed' | 'figure_reuse_allowed' | 'derivative_illustration_allowed' | 'full_public_processing_allowed' | 'restricted_blocked';
export type JournalSourceConfidence = 'verified' | 'editor_claimed' | 'author_claimed' | 'publicly_accessible' | 'machine_parsed_only' | 'conflict' | 'expired' | 'revoked';
export interface JournalArticleSourceRecord { id: string; sourceType: JournalSourceType; title?: string | null; url?: string | null; fileId?: string | null; uploadedBy?: string | null; uploadedAt?: string | null; rightsStatus: JournalRightsStatus; sourceConfidence: JournalSourceConfidence; permissions: { internalProcessing: boolean; derivativeGeneration: boolean; publicSource: boolean; publicDerivative: boolean; externalProcessing: boolean; figureReuse: boolean; derivativeIllustration: boolean }; evidence: { statement: string; license?: string | null; verifiedBy?: string | null; verifiedAt?: string | null; expiresAt?: string | null }; notes?: string | null; activeForGeneration: boolean; }
export interface JournalSourceHistoryEntry { id: string; action: string; actorId?: string | null; createdAt: string; after?: { sourceId?: string; sourceType?: JournalSourceType; before?: JournalArticleSourceRecord; after?: JournalArticleSourceRecord } | null; }
export interface ArticleProcessingCapability { canGenerateMetadataPage: boolean; canGenerateAbstractSummary: boolean; canGenerateFullSixFields: boolean; canGenerateFigureExplanation: boolean; canGenerateReproducibilityField: boolean; canGenerateDerivativeIllustration: boolean; canPublishPublicSummary: boolean; canPublishFullInterpretation: boolean; canPublishFigures: boolean; canExposeViaApi: boolean; limitations: string[]; blockingReasons: string[]; lastEvaluatedAt: string; }
export type JournalRecommendedAction = 'process_now' | 'process_after_confirmation' | 'request_more_sources' | 'rights_review_required' | 'metadata_only' | 'blocked';
export interface JournalArticlePriority { journalArticleId: string; sourceCompletenessScore: number; rightsClarityScore: number; recencyScore: number; showcaseValueScore: number; academicCentralityScore: number; parseSuccessScore: number; editorPriorityScore: number; topicMatchScore: number; totalScore: number; priorityLevel: 'P0' | 'P1' | 'P2' | 'P3' | 'blocked'; recommendedAction: JournalRecommendedAction; reasons: string[]; unknownDimensions: string[]; estimatedCreditCost: number; deferredUntil: string | null; lastCalculatedAt: string; override: { editorPriorityScore: number; deferredUntil: string | null; reason: string } | null; }
export interface JournalProcessingPriorityItem { article: { id: string; title: string; publishedDate?: string | null; revision: number; reviewState: JournalArticle['reviewState']; sourceKind: string }; priority: JournalArticlePriority; }
export interface JournalServicePlan { planChoice: 'free' | 'starter' | 'pro' | 'premium' | 'custom'; requestedPlanChoice?: 'free' | 'starter' | 'pro' | 'premium' | 'custom' | null; commercialModel: 'manual_quote'; validUntil: string | null; credits: { available: number; reserved: number; consumed: number; expired: number; monthlyUsed: number }; grants: Array<{ id: string; amount: number; remaining: number; reserved: number; consumed: number; expiresAt: string | null }>; ledger: Array<{ id: string; kind: string; amount: number; createdAt: string; note?: string | null }>; storage: { usedBytes: string; limitBytes: string }; serviceRequests: Array<JournalServiceRequest & { planChoice?: string }>; }
export interface JournalMember { userId: string; email: string; displayName: string; role: JournalRole; joinedAt: string; }
export interface JournalImportPreview { input: string; status: 'ready' | 'imported' | 'duplicate' | 'failed'; metadata?: JournalArticle['metadata']; articleId?: string; error?: string; }

function query(input: Record<string, string | number | undefined>) { const p = new URLSearchParams(); Object.entries(input).forEach(([k, v]) => { if (v !== undefined && v !== '') p.set(k, String(v)); }); return p.toString() ? `?${p}` : ''; }
export function listJournals(input: { query?: string; subject?: string; cursor?: string; limit?: number } = {}) { return apiRequest<{ items: JournalSummary[]; nextCursor: string | null }>(`/api/journals${query(input)}`); }
export function getJournal(slug: string) { return apiRequest<{ journal: JournalPublic }>(`/api/journals/${encodeURIComponent(slug)}`); }
export function getJournalArticles(journalId: string, input: { cursor?: string; limit?: number } = {}) { return apiRequest<{ items: JournalArticle[]; nextCursor: string | null }>(`/api/journals/${encodeURIComponent(journalId)}/articles${query(input)}`); }
export function listMyJournals() { return apiRequest<{ items: JournalSummary[] }>('/api/journals/mine'); }
export function listApplications() { return apiRequest<{ items: JournalApplication[] }>('/api/journals/applications'); }
export function getJournalApplication(id: string) { return apiRequest<{ application: JournalApplication }>(`/api/journals/applications/${encodeURIComponent(id)}`); }
export function saveApplication(input: Partial<JournalApplicationInput> & { revision?: number }, id?: string) { return apiRequest<{ application: JournalApplication }>(id ? `/api/journals/applications/${id}` : '/api/journals/applications', { method: id ? 'PATCH' : 'POST', body: JSON.stringify(input) }); }
export function submitApplication(id: string, input: { revision: number; submissionKey: string }) { return apiRequest<{ application: JournalApplication }>(`/api/journals/applications/${id}/submit`, { method: 'POST', body: JSON.stringify(input) }); }
export function getJournalDashboard(id: string) { return apiRequest<JournalDashboard>(`/api/journals/${encodeURIComponent(id)}/manage`); }
export function updateJournalHomepage(id: string, input: { revision: number } & Partial<Pick<JournalSummary, 'nameZh' | 'nameEn' | 'websiteUrl' | 'publisherName' | 'sponsorName' | 'subjects' | 'description' | 'logoUrl'>>) { return apiRequest<{ journal: JournalSummary }>(`/api/journals/${id}/homepage`, { method: 'PATCH', body: JSON.stringify(input) }); }
export function activateJournal(id: string) { return apiRequest<{ journal: JournalSummary }>(`/api/journals/${id}/activate`, { method: 'POST', body: '{}' }); }
export function listJournalMembers(id: string) { return apiRequest<{ items: JournalMember[] }>(`/api/journals/${id}/members`); }
export function addJournalMember(id: string, input: { email: string; role: Exclude<JournalRole, 'owner'> }) { return apiRequest<{ member: JournalMember }>(`/api/journals/${id}/members`, { method: 'POST', body: JSON.stringify(input) }); }
export function updateJournalMember(id: string, userId: string, role: Exclude<JournalRole, 'owner'>) { return apiRequest<{ member: JournalMember }>(`/api/journals/${id}/members/${userId}`, { method: 'PATCH', body: JSON.stringify({ role }) }); }
export function removeJournalMember(id: string, userId: string) { return apiRequest<void>(`/api/journals/${id}/members/${userId}`, { method: 'DELETE' }); }
export function transferJournalOwner(id: string, input: { newOwnerId: string; reason: string }) { return apiRequest<{ journal: JournalSummary }>(`/api/journals/${id}/owner`, { method: 'POST', body: JSON.stringify(input) }); }
export function getJournalArticle(id: string, articleId: string) { return apiRequest<{ article: JournalArticle }>(`/api/journals/${encodeURIComponent(id)}/articles/${encodeURIComponent(articleId)}`); }
export function updateJournalArticle(id: string, articleId: string, input: { revision: number; metadata?: Partial<JournalArticle['metadata']>; directoryVisible?: boolean; source?: JournalArticle['source']; rights?: ArticleRights; draft?: JournalDraft }) { return apiRequest<{ article: JournalArticle }>(`/api/journals/${id}/articles/${articleId}`, { method: 'PATCH', body: JSON.stringify(input) }); }
export async function uploadJournalSourceFile(id: string, articleId: string, input: { revision: number; requestKey: string; file: File }) { const xhr = new XMLHttpRequest(); await prepareProtectedXhr(xhr, 'POST', `/api/journals/${id}/articles/${articleId}/source-file`); const body = new FormData(); body.append('revision', String(input.revision)); body.append('requestKey', input.requestKey); body.append('file', input.file, input.file.name); return new Promise<{ job: { id: string; state: string } }>((resolve, reject) => { xhr.onerror = () => reject(new Error('来源文件上传失败')); xhr.onload = () => { if (xhr.status >= 200 && xhr.status < 300) resolve(JSON.parse(xhr.responseText) as { job: { id: string; state: string } }); else reject(new Error('来源文件上传失败')); }; xhr.send(body); }); }
export function importJournalDois(id: string, dois: string[]) { return apiRequest<{ items: Array<{ input: string; status: 'imported' | 'duplicate' | 'failed'; articleId?: string; error?: string }> }>(`/api/journals/${id}/articles/import`, { method: 'POST', body: JSON.stringify({ dois }) }); }
export function previewJournalDois(id: string, dois: string[]) { return apiRequest<{ items: JournalImportPreview[] }>(`/api/journals/${id}/articles/preview`, { method: 'POST', body: JSON.stringify({ dois }) }); }
export function createAiDraft(id: string, articleId: string, input: { revision: number; language: 'zh' | 'en'; requestKey: string; retryOf?: string }) { return apiRequest<{ job: { id: string; status: string } }>(`/api/journals/${id}/articles/${articleId}/ai-drafts`, { method: 'POST', body: JSON.stringify(input) }); }
export function createJournalProcessingJob(id: string, articleId: string, input: { revision: number; language: 'zh' | 'en'; requestKey: string; retryOf?: string; manualConfirmation: boolean }) { return apiRequest<{ job: { id: string; status: string } }>(`/api/journals/${id}/articles/${articleId}/processing-jobs`, { method: 'POST', body: JSON.stringify(input) }); }
export function reviewJournalArticle(id: string, articleId: string, input: { revision: number; decision: 'submit' | 'approve' | 'request_changes'; note: string }) { return apiRequest(`/api/journals/${id}/articles/${articleId}/review`, { method: 'POST', body: JSON.stringify(input) }); }
export function assignJournalReviewer(id: string, articleId: string, input: { revision: number; reviewerId: string }) { return apiRequest<{ article: JournalArticle }>(`/api/journals/${id}/articles/${articleId}/reviewer`, { method: 'POST', body: JSON.stringify(input) }); }
export function publishJournalArticle(id: string, articleId: string, input: { revision: number; requestKey: string }) { return apiRequest<{ release: { versionNo: number; publicId: string; url: string } }>(`/api/journals/${id}/articles/${articleId}/publish`, { method: 'POST', body: JSON.stringify({ ...input, humanConfirmed: true }) }); }
export function requestJournalService(id: string, input: { annualVolume: number; language: string; figureScale: string; services: string[]; notes: string; requestKey: string; planChoice?: JournalServicePlan['planChoice'] }) { return apiRequest<{ request: JournalServiceRequest }>(`/api/journals/${id}/service-requests`, { method: 'POST', body: JSON.stringify(input) }); }
export function getJournalArticleSources(id: string, articleId: string) { return apiRequest<{ sources: JournalArticleSourceRecord[]; capability: ArticleProcessingCapability; history: JournalSourceHistoryEntry[]; articleRevision: number }>(`/api/journals/${encodeURIComponent(id)}/articles/${encodeURIComponent(articleId)}/sources`); }
export function addJournalArticleSource(id: string, articleId: string, input: { revision: number; source: Omit<JournalArticleSourceRecord, 'id' | 'fileId' | 'uploadedBy' | 'uploadedAt'> }) { return apiRequest<{ sources: JournalArticleSourceRecord[]; capability: ArticleProcessingCapability; articleRevision: number }>(`/api/journals/${encodeURIComponent(id)}/articles/${encodeURIComponent(articleId)}/sources`, { method: 'POST', body: JSON.stringify(input) }); }
export function updateJournalArticleSourceRights(id: string, articleId: string, sourceId: string, input: { revision: number; rightsStatus: JournalRightsStatus; sourceConfidence: JournalSourceConfidence; permissions: JournalArticleSourceRecord['permissions']; evidence: JournalArticleSourceRecord['evidence']; notes?: string; activeForGeneration?: boolean }) { return apiRequest<{ sources: JournalArticleSourceRecord[]; capability: ArticleProcessingCapability; articleRevision: number }>(`/api/journals/${encodeURIComponent(id)}/articles/${encodeURIComponent(articleId)}/sources/${encodeURIComponent(sourceId)}/rights`, { method: 'PATCH', body: JSON.stringify(input) }); }
export function recalculateJournalProcessingCapability(id: string, articleId: string, input: { revision: number }) { return apiRequest<{ capability: ArticleProcessingCapability }>(`/api/journals/${encodeURIComponent(id)}/articles/${encodeURIComponent(articleId)}/processing-capability/recalculate`, { method: 'POST', body: JSON.stringify(input) }); }
export function listJournalProcessingPriorities(id: string, input: { cursor?: string; limit?: number } = {}) { return apiRequest<{ items: JournalProcessingPriorityItem[]; nextCursor: string | null }>(`/api/journals/${encodeURIComponent(id)}/processing-priorities${query(input)}`); }
export function updateJournalPriorityOverride(id: string, articleId: string, input: { editorPriorityScore: number; deferredUntil?: string | null; reason: string }) { return apiRequest<{ priority: JournalArticlePriority }>(`/api/journals/${encodeURIComponent(id)}/articles/${encodeURIComponent(articleId)}/priority-override`, { method: 'POST', body: JSON.stringify(input) }); }
export function getJournalServicePlan(id: string) { return apiRequest<JournalServicePlan>(`/api/journals/${encodeURIComponent(id)}/service-plan`); }
export function createManualJournalArticle(id: string, metadata: JournalArticle['metadata']) { return apiRequest<{ article: JournalArticle }>(`/api/journals/${id}/articles`, { method: 'POST', body: JSON.stringify({ metadata }) }); }
export function cancelJournalJob(id: string, jobId: string) { return apiRequest<{ job: { id: string; state: string } }>(`/api/journals/${id}/jobs/${jobId}/cancel`, { method: 'POST', body: '{}' }); }
export function restrictJournalArticle(id: string, articleId: string, input: { state: 'restricted' | 'withdrawn'; reason: string }) { return apiRequest<{ article: JournalArticle }>(`/api/journals/${id}/articles/${articleId}/restrict`, { method: 'POST', body: JSON.stringify(input) }); }
export function listAdminJournals() { return apiRequest<{ items: JournalSummary[] }>('/api/admin/journals'); }
export function reopenJournalApplication(id: string, input: { expectedRevision: number; reason: string }) { return apiRequest<{ application: JournalApplication }>(`/api/admin/journals/applications/${id}/reopen`, { method: 'POST', body: JSON.stringify(input) }); }
export function reviewJournalApplication(id: string, input: { decision: 'approved' | 'rejected' | 'needs_information'; reason?: string; slug?: string }) { return apiRequest<{ application: JournalApplication; journal?: JournalSummary }> (`/api/admin/journals/applications/${id}/review`, { method: 'POST', body: JSON.stringify(input) }); }
export function setAdminJournalState(id: string, input: { action: 'pause' | 'close' | 'reverify' | 'resume'; reason: string }) { return apiRequest<{ journal: JournalSummary }>(`/api/admin/journals/${id}/state`, { method: 'POST', body: JSON.stringify(input) }); }
export function grantJournalCredits(id: string, input: { amount: number; expiresAt: string; reason: string; requestKey: string; serviceRequestId?: string }) { return apiRequest(`/api/admin/journals/${id}/grants`, { method: 'POST', body: JSON.stringify(input) }); }
export function listAdminServiceRequests() { return apiRequest<{ items: JournalServiceRequest[] }>('/api/admin/journals/service-requests'); }
export function reviewAdminServiceRequest(id: string, input: { status: 'quoted' | 'rejected' | 'cancelled'; expectedStatus: JournalServiceRequest['status']; note: string }) { return apiRequest<{ request: JournalServiceRequest }>(`/api/admin/journals/service-requests/${id}/review`, { method: 'POST', body: JSON.stringify(input) }); }

export interface JournalFeedbackItem { id: string; articleId: string; versionNo: number; content: string; status: 'open' | 'resolved' | 'declined'; response: string | null; createdAt: string; respondedAt: string | null; reporterId: string; }
export function createJournalFeedback(journalId: string, articleId: string, input: { versionNo: number; content: string; requestKey: string }) { return apiRequest<{ feedback: JournalFeedbackItem }>(`/api/journals/${journalId}/articles/${articleId}/feedback`, { method: 'POST', body: JSON.stringify(input) }); }
export function listJournalFeedback(journalId: string, cursor?: string) { return apiRequest<{ items: JournalFeedbackItem[]; role: 'editor' | 'reporter'; nextCursor: string | null }>(`/api/journals/${journalId}/feedback${query({ cursor, limit: 20 })}`); }
export function respondJournalFeedback(journalId: string, feedbackId: string, input: { expectedStatus: JournalFeedbackItem['status']; status: 'resolved' | 'declined'; response: string }) { return apiRequest<{ feedback: JournalFeedbackItem }>(`/api/journals/${journalId}/feedback/${feedbackId}/respond`, { method: 'POST', body: JSON.stringify(input) }); }
