import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { spawnSync } from 'node:child_process';
import { join, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import process from 'node:process';
import test from 'node:test';

const patcher = resolve(import.meta.dirname, '..', 'patch-upstream.py');
const python = process.platform === 'win32' ? 'python' : 'python3';

function runPython(args, env = process.env) {
  return spawnSync(python, args, { encoding: 'utf8', env });
}

test('upstream patch connects the controlled institutional context and reaps browser workers', async () => {
  const root = await mkdtemp(join(tmpdir(), 'scansci-upstream-patch-'));
  const packageRoot = join(root, 'scansci_pdf');
  const sources = join(packageRoot, 'sources');
  const institutional = join(packageRoot, 'institutional');
  try {
    await mkdir(sources, { recursive: true });
    await mkdir(institutional, { recursive: true });
    await writeFile(join(packageRoot, 'log.py'), [
      'class Log:',
      '    def info(self, message): pass',
      'def get_logger(): return Log()',
      '',
    ].join('\n'));
    await writeFile(join(packageRoot, 'network.py'), [
      'USER_AGENT = "fixture-agent"',
      'def request_timeout(config): return (3, 7)',
      '',
    ].join('\n'));
    await writeFile(join(packageRoot, '__init__.py'), [
      'import os as _os',
      '_os.environ["NO_PROXY"] = "*"',
      '_os.environ["no_proxy"] = "*"',
      '',
    ].join('\n'));
    await writeFile(join(packageRoot, '_publisher_strategies_core.py'), [
      'from __future__ import annotations',
      'import contextlib',
      'import json',
      'import re',
      'import threading',
      'import time',
      'from pathlib import Path',
      'from typing import Any',
      '_IDP_MAP: dict[str, str] = {',
      '    "清华大学": "Tsinghua", "北京大学": "Peking", "浙江大学": "Zhejiang",',
      '    "复旦大学": "Fudan",',
      '}',
      '_INSTITUTION_CLICK_JS: str = (',
      '    "(name) => {"',
      '    "  const items = document.querySelectorAll("',
      '    "    \'[class*=\\"result\\"], [class*=\\"suggestion\\"], [class*=\\"federation\\"], li, a, button\');"',
      '    "  for (const el of items) {"',
      '    "    const text = el.textContent || \'\';"',
      '    "    if (text.includes(name) && el.offsetParent !== null) {"',
      '    "      el.click();"',
      '    "      return text.trim().substring(0, 60);"',
      '    "    }"',
      '    "  }"',
      '    "  return null;"',
      '    "}"',
      ')',
      'def _fixture_institution_login(page, idp_en, config):',
      '    for _attempt in range(3):',
      '        try:',
      '            if True:',
      '                if True:',
      '                    si = (page.query_selector(\'#searchInstitution\')',
      '                          or page.query_selector(\'input[placeholder*="University"]\')',
      '                          or page.query_selector(\'input[placeholder*="Organization"]\'))',
      '                    if si:',
      '                        si.fill(idp_en)',
      '                        time.sleep(3)',
      '                        # Use keyboard to select first result (more reliable than click)',
      '                        si.press(\'ArrowDown\')',
      '                        time.sleep(1)',
      '                        si.press(\'Enter\')',
      '                        time.sleep(5)',
      '            break',
      '        except Exception as e:',
      '            if "navigation" in str(e).lower() or "destroyed" in str(e).lower():',
      '                time.sleep(5)',
      '                continue',
      '            break',
      '    if True:',
      '        if True:',
      '            logged_in = False',
      '            for _ in range(100):',
      '                time.sleep(3)',
      '                try:',
      '                    cur_title = page.title()',
      '                    cur_url = page.url',
      '                except Exception:',
      '                    time.sleep(2)',
      '                    continue',
      '                if cur_title == "ready" and cur_url == "ready":',
      '                    logged_in = True',
      '                    break',
      '    return logged_in',
      'def _headless_selection_fixture(evaluate_js, tab_id, idp_en, config):',
      '    clicked = evaluate_js(tab_id, f"""',
      '        (() => {{',
      '                const items = document.querySelectorAll(\'[class*="result"], [class*="suggestion"], [class*="federation"], li, a, button\');',
      '                for (const el of items) {{',
      '                    const text = el.textContent || \'\';',
      '                    if (text.includes(name) && el.offsetParent !== null) {{',
      '                        el.click();',
      '                        return text.trim().substring(0, 60);',
      '                    }}',
      '                }}',
      '        }})()',
      '    """, config)',
      '    return clicked',
      'def _visible_institutional_fixture(page, idp_en, config, publisher):',
      '    if True:',
      '        if True:',
      '            if page:',
      '                page.evaluate(f"""',
      '                    (name) => {{',
      '                        const items = document.querySelectorAll(\'[class*="result"], [class*="suggestion"], li, a, button\');',
      '                        for (const el of items) {{',
      '                            if (el.textContent.includes(name) && el.offsetParent !== null) {{',
      '                                el.click();',
      '                                return true;',
      '                            }}',
      '                        }}',
      '                        return false;',
      '                    }}',
      '                """, idp_en)',
      '                time.sleep(5)',
      '    if True:',
      '        for i in range(100):',
      '            time.sleep(3)',
      '            try:',
      '                title = page.title()',
      '                break',
      '            except Exception:',
      '                return False',
      '    return True',
      'def _visible_browser_fixture(sso_page, idp_en, config, publisher):',
      '    if True:',
      '        if True:',
      '            if True:',
      '                for _ in range(1):',
      '                    clicked = sso_page.evaluate(f"""',
      '                        (name) => {{',
      '                            const items = document.querySelectorAll(\'[class*="result"], [class*="suggestion"], [class*="federation"], li, a, button\');',
      '                            for (const el of items) {{',
      '                                if (el.textContent.includes(name) && el.offsetParent !== null) {{',
      '                                    el.click();',
      '                                    return true;',
      '                                }}',
      '                            }}',
      '                            return false;',
      '                        }}',
      '                    """, idp_en)',
      '                    if clicked:',
      '                        log.info(f"   [{publisher}] selected institution \'{idp_en}\'")',
      '                        time.sleep(5)',
      '                        break',
      '    if True:',
      '        login_ok = False',
      '        for i in range(100):',
      '            time.sleep(3)',
      '            # Check ALL pages in context — SSO may happen in any tab',
      '            login_ok = True',
      '            break',
      '    return login_ok',
      'def _restore_cookies_to_context(context: Any, config: dict[str, Any]) -> None:',
      '    try:',
      '        from .browser_cookies import load_saved_cookies',
      '        saved = load_saved_cookies(config)',
      '        if saved:',
      '            pw_cookies = []',
      '            for c in saved:',
      '                pw_c = {"name": c.get("name", ""), "value": c.get("value", ""),',
      '                         "domain": c.get("domain", ""), "path": c.get("path", "/")}',
      '                if pw_c["domain"]:',
      '                    pw_cookies.append(pw_c)',
      '            if pw_cookies:',
      '                context.add_cookies(pw_cookies)',
      '    except Exception:',
      '        pass',
      'from .browser_engine import FixtureProc',
      'class FixtureTransport:',
      '    def __init__(self, proc): self._proc = proc',
      'class FixtureConnection:',
      '    def __init__(self, proc): self._transport = FixtureTransport(proc)',
      'class FixtureImpl:',
      '    def __init__(self, proc): self._connection = FixtureConnection(proc)',
      'class FixtureContext:',
      '    def __init__(self, fail_new_page=False, proc=None):',
      '        self.proc = proc or FixtureProc()',
      '        self._impl_obj = FixtureImpl(self.proc)',
      '        self.fail_new_page = fail_new_page',
      '    def close(self):',
      '        if scenario == "successful_close":',
      '            self.proc.returncode = 0',
      '            return',
      '        raise RuntimeError("fixture close failure")',
      '    def new_page(self):',
      '        if self.fail_new_page: raise RuntimeError("fixture page failure")',
      '        return None',
      'class FixtureBrowser:',
      '    def __init__(self, fail_new_context=False):',
      '        self.proc = FixtureProc()',
      '        self._impl_obj = FixtureImpl(self.proc)',
      '        self.fail_new_context = fail_new_context',
      '    def close(self): raise RuntimeError("fixture close failure")',
      '    def new_context(self, viewport=None):',
      '        if self.fail_new_context: raise RuntimeError("fixture context failure")',
      '        return FixtureContext(proc=self.proc)',
      '_HAS_CLOAKBROWSER = True',
      'def _get_profile_dir(config, publisher): return Path("/profile")',
      'scenario = "happy"',
      'created = []',
      'def launch_persistent_context(*args, **kwargs):',
      '    ctx = FixtureContext(fail_new_page=scenario in ("persistent_page_fail", "fallback_context_fail"))',
      '    created.append(ctx)',
      '    return ctx',
      'def launch(*args, **kwargs):',
      '    browser = FixtureBrowser(fail_new_context=scenario == "fallback_context_fail")',
      '    created.append(browser)',
      '    return browser',
      'class Log:',
      '    def info(self, message): pass',
      'log = Log()',
      '@contextlib.contextmanager',
      'def _visible_browser(config: dict[str, Any], publisher: str, *, viewport: dict | None = None):',
      '    """Open visible CloakBrowser with persistent profile. Falls back to ephemeral."""',
      '    if not _HAS_CLOAKBROWSER:',
      '        raise RuntimeError("cloakbrowser not installed. Run: pip install cloakbrowser")',
      '    profile_dir = _get_profile_dir(config, publisher)',
      '    browser = None',
      '',
      '    try:',
      '        ctx = launch_persistent_context(',
      '            str(profile_dir),',
      '            headless=False, humanize=True,',
      '            args=["--disable-features=CrossOriginOpenerPolicy"],',
      '        )',
      '        page = ctx.new_page()',
      '        log.info(f"   [{publisher}] persistent browser profile: {profile_dir}")',
      '        # Ensure cookies are loaded from saved file',
      '        _restore_cookies_to_context(ctx, config)',
      '    except Exception as _e:',
      '        log.info(f"   [{publisher}] persistent context unavailable ({_e}), using ephemeral")',
      '        _vp = viewport or {"width": 1440, "height": 900}',
      '        browser = launch(headless=False, humanize=True,',
      '                         args=["--disable-features=CrossOriginOpenerPolicy"])',
      '        ctx = browser.new_context(viewport=_vp)',
      '        _restore_cookies_to_context(ctx, config)',
      '        page = ctx.new_page()',
      '',
      '    try:',
      '        yield ctx, page',
      '    finally:',
      '        try:',
      '            if browser:',
      '                browser.close()',
      '            else:',
      '                ctx.close()',
      '        except Exception:',
      '            pass',
      'def create_tab(url, config, timeout): return "tab"',
      'config = {}',
      'tab_id = create_tab("https://www.google.com/", config, timeout=15.0)',
      '',
    ].join('\n'));
    await writeFile(join(packageRoot, 'browser_engine.py'), [
      'import os',
      'import shutil',
      'import subprocess',
      'from pathlib import Path',
      'from typing import Any',
      'class FixtureSubprocess:',
      '    calls = []',
      '    @classmethod',
      '    def run(cls, *args, **kwargs): cls.calls.append((args, kwargs))',
      'subprocess = FixtureSubprocess',
      'class FixtureProc:',
      '    next_pid = 1000',
      '    def __init__(self, returncode=None):',
      '        self.returncode = returncode',
      '        self.pid = FixtureProc.next_pid',
      '        FixtureProc.next_pid += 1',
      '        self.killed = False',
      '    def kill(self): self.killed = True',
      'class TLS: pass',
      '_tls = TLS()',
      'def _unregister_browser(browser): pass',
      'def _tree_kill(proc: Any) -> None:',
      '    """Force-kill a driver process and its whole child tree (Windows-safe)."""',
      '    if proc is None or proc.poll() is not None:',
      '        return',
      '    if os.name == "nt":',
      '        subprocess.run(',
      '            ["taskkill", "/F", "/T", "/PID", str(proc.pid)],',
      '            capture_output=True, timeout=15,',
      '        )',
      '    else:',
      '        proc.kill()',
      'def configure_context(browser, config):',
      '    proxy = config.get("browser_static_proxy", "")',
      '    context = browser.new_context()',
      '',
      '    # Launching the sync API leaves its dispatcher event loop "running" in',
      '    return context',
      'def _parse_netscape_cookies(text):',
      '    assert text == "fixture-session"',
      '    return [{"name": "institution", "value": "ok", "domain": ".example", "path": "/", "expires": 0}]',
      'def shutdown_shared_browser():',
      '    """Shut down the current thread\'s browser. Call on thread exit or process exit."""',
      '    browser = getattr(_tls, "browser", None)',
      '    if browser is not None:',
      '        try:',
      '            browser.close()',
      '        except Exception:',
      '            pass',
      '        _unregister_browser(browser)',
      '        _tls.browser = None',
      '        _tls.context = None',
      '        logger.info("browser_engine: browser shut down")',
      'class Logger:',
      '    def info(self, message): pass',
      'logger = Logger()',
      '',
    ].join('\n'));
    await writeFile(join(packageRoot, 'browser_backend.py'), [
      'import os',
      'BACKEND_PATCHRIGHT = "patchright"',
      'BACKEND_CAMOUFOX = "camoufox"',
      'def resolve_backend(config): return BACKEND_PATCHRIGHT',
      'def _launch_patchright(config, headless, proxy, args, **kwargs): return proxy',
      'def _launch_patchright_persistent(config, user_data_dir, headless, proxy, args, **kwargs): return proxy',
      '',
      '# ---------------------------------------------------------------------------',
      '# Public entry points',
      '# ---------------------------------------------------------------------------',
      '',
      'def launch(',
      '    *,',
      '    headless: bool = True,',
      '    proxy = None,',
      '    args = None,',
      '    humanize: bool = True,',
      '    config = None,',
      '    **kwargs,',
      '):',
      '    """Launch.',
      '',
      '    ``playwright.chromium.launch()`` / ``cloakbrowser.launch()``.',
      '    """',
      '    backend = resolve_backend(config)',
      '    if backend == BACKEND_PATCHRIGHT:',
      '        return _launch_patchright(config, headless=headless, proxy=proxy, args=args, **kwargs)',
      '',
      'def launch_persistent_context(',
      '    user_data_dir: str,',
      '    *,',
      '    headless: bool = True,',
      '    proxy = None,',
      '    args = None,',
      '    humanize: bool = True,',
      '    config = None,',
      '    **kwargs,',
      '):',
      '    """Persistent context.',
      '',
      '    Same contract as ``playwright.chromium.launch_persistent_context()``.',
      '    """',
      '    backend = resolve_backend(config)',
      '    if backend == BACKEND_PATCHRIGHT:',
      '        return _launch_patchright_persistent(',
      '            config, user_data_dir, headless=headless, proxy=proxy, args=args, **kwargs',
      '        )',
      '',
    ].join('\n'));
    await writeFile(join(packageRoot, 'browser_cookies.py'), [
      'from __future__ import annotations',
      'import json',
      'import time',
      'from pathlib import Path',
      'from typing import Any',
      'def _is_cookie_valid(cookie, now): return not cookie.get("expires") or cookie["expires"] > now',
      'def load_saved_cookies(config: dict[str, Any]) -> list[dict[str, Any]]:',
      '    """Load previously saved publisher cookies, filtering out expired ones."""',
      '    from .config import DATA_DIR',
      '    cookie_file = Path(config.get("cache_dir", str(DATA_DIR / "cache"))) / "publisher_cookies.json"',
      '    if not cookie_file.exists():',
      '        return []',
      '    try:',
      '        cookies = json.loads(cookie_file.read_text(encoding="utf-8"))',
      '    except Exception:',
      '        return []',
      '    now = time.time()',
      '    return [c for c in cookies if _is_cookie_valid(c, now)]',
      '',
    ].join('\n'));
    await writeFile(join(packageRoot, 'config.py'), [
      'from pathlib import Path',
      'DATA_DIR = Path("/unused")',
      '',
    ].join('\n'));
    await writeFile(join(packageRoot, 'browser_login.py'), [
      'from __future__ import annotations',
      'import json',
      'import time',
      'import atexit',
      'from pathlib import Path',
      'from typing import Any',
      'def _save_cookies_netscape(cookies: list[dict[str, Any]], cookie_file: Path) -> None:',
      '    """Save cookies in Netscape format (CloakBrowser import compatible)."""',
      '    from .browser_cookies import cookies_to_netscape',
      '    cookie_file.write_text(cookies_to_netscape(cookies), encoding="utf-8")',
      '',
      '',
      'def _import_to_browser(cookie_file: Path, config: dict[str, Any]) -> int:',
      '    return 0',
      'class Context:',
      '    def __init__(self): self.added = []',
      '    def add_cookies(self, cookies): self.added.extend(cookies)',
      '    def new_page(self): return object()',
      'class Browser:',
      '    def __init__(self): self.context = Context()',
      '    def new_context(self): return self.context',
      'def launch(**kwargs): return Browser()',
      'def open_login_browser(url, config, *, cookie_file, **kwargs):',
      '    try:',
      '        browser = launch(headless=False, humanize=True,',
      '                         args=["--disable-features=CrossOriginOpenerPolicy"])',
      '        context = browser.new_context()',
      '        page = context.new_page()',
      '        return context, page',
      '    except Exception:',
      '        return None',
      '',
    ].join('\n'));
    await writeFile(join(institutional, '__init__.py'), '');
    await writeFile(join(institutional, 'publisher_batch.py'), [
      'import time',
      'class PublisherBatchDownloader:',
      '    def __init__(self, config):',
      '        self.config = config',
      '        self.login_timeout_sec = 300',
      '        self._progress_active = False',
      '',
      '    def run_records(self): return None',
      '    def _event(self, *args): pass',
      '    def _title(self, page): return "challenge"',
      '    def _dismiss_cookie_banners(self, page, result): pass',
      '    def _click_optional_continue(self, page, result): pass',
      '    def _is_challenge_page(self, page): return True',
      '    def _complete_login_from_current_page(self, page, result):',
      '        deadline = time.time() + self.login_timeout_sec',
      '        last_state = ""',
      '        last_auto_action = ""',
      '        last_auto_action_at = 0.0',
      '        while time.time() < deadline:',
      '            time.sleep(3)',
      '            marker = f"{self._title(page)} | {getattr(page, \'url\', \'\')[:160]}"',
      '            return True',
      '        return False',
      '    def _wait_for_challenge(self, page, result, *, deadline=None):',
      '        wait_interval_sec = 5',
      '        max_checks = 8',
      '        waited = False',
      '        try:',
      '            for index in range(max_checks):',
      '                if self._is_challenge_page(page):',
      '                    waited = True',
      '                    time.sleep(wait_interval_sec)',
      '                    continue',
      '                return True',
      '            return not self._is_challenge_page(page)',
      '        finally:',
      '            pass',
      '',
    ].join('\n'));
    await writeFile(join(sources, '__init__.py'), [
      'import inspect',
      'import json',
      'import threading',
      'import time',
      'from concurrent.futures import ThreadPoolExecutor, as_completed',
      'from pathlib import Path',
      '_BROWSER_SOURCE_LABELS = frozenset({',
      '    "GenericBrowser", "WebVPN", "CARSI", "EZProxy",',
      '})',
      '_browser_semaphore = threading.Semaphore(0)',
      'def safe_filename(doi): return doi.replace("/", "_").replace(".", "_")',
      'def _neg_blocked(label, doi): return False',
      'class FixtureLog:',
      '    def info(self, message): pass',
      'log = FixtureLog()',
      'def _request_output_paths(all_sources, target_dir, doi):',
      '    if not all_sources:',
      '        return None',
      '',
      '    # If only one source, run directly',
      '    if len(all_sources) == 1:',
      '        fn, label, tier_label, timeout = all_sources[0]',
      '        src_output = target_dir / f"{safe_filename(doi)}_{label}.pdf"',
      '        return [src_output]',
      '    paths = []',
      '    if True:',
      '        for fn, label, tier_label, tier_timeout in all_sources:',
      '            if _neg_blocked(label, doi):',
      '                log.info(f"   SKIP {label} (negative cache: recently failed for this publisher)")',
      '                continue',
      '            src_output = target_dir / f"{safe_filename(doi)}_{label}.pdf"',
      '            paths.append(src_output)',
      '    return paths',
      'def _get_browser_semaphore(config): return _browser_semaphore',
      'def _grace_fixture(all_sources):',
      '    has_browser = any("Browser" in lbl for _, lbl, _, _ in all_sources)',
      '    return has_browser',
      'def _try_source(source_fn, doi, output_path, config, label, use_tor=False):',
      '    from .scoring import record_result, classify_error, get_user_advice',
      '    is_browser = label in _BROWSER_SOURCE_LABELS',
      '    sem = _get_browser_semaphore(config) if is_browser else None',
      '    if sem:',
      '        sem.acquire()',
      '    try:',
      '        sig = inspect.signature(source_fn)',
      '        if "use_tor" in sig.parameters:',
      '            return source_fn(doi, output_path, config, use_tor=use_tor)',
      '        return source_fn(doi, output_path, config)',
      '    finally:',
      '        if sem: sem.release()',
      'def _race_worker_fixture(cancel_event, doi, config, use_tor):',
      '    def _try_and_publish(fn, label, src_output):',
      '        # Skip if another source already succeeded',
      '        if cancel_event.is_set():',
      '            return None',
      '        result = _try_source(fn, doi, src_output, config, label, use_tor=use_tor)',
      '        if result and not result.get("success"):',
      '            return result',
      '        return result',
      '    return _try_and_publish',
      'def _race_cleanup_fixture(futures, pool, cancel_event, all_done_event):',
      '    try:',
      '        return None',
      '    finally:',
      '        # Never block termination on sources that refuse to return: cancel',
      '        # pending futures and waive stragglers. Their own I/O deadlines',
      '        # (connect/read timeouts, stream deadline in pdf_utils) bound how long',
      '        # an abandoned worker thread can outlive the race.',
      '        alive = [f for f in futures if not f.done()]',
      '        if alive:',
      '            pass',
      '        pool.shutdown(wait=False, cancel_futures=True)',
      'def exercise(is_browser, sem):',
      '    try:',
      '        return "ok"',
      '    finally:',
      '        if sem:',
      '            sem.release()',
      '',
    ].join('\n'));
    await writeFile(join(sources, 'scoring.py'), [
      'def record_result(*args, **kwargs): pass',
      'def classify_error(*args, **kwargs): return "fixture"',
      'def get_user_advice(*args, **kwargs): return "fixture"',
      '',
    ].join('\n'));
    await writeFile(join(sources, 'carsi.py'), [
      'import threading',
      'import time',
      'from .._publisher_strategies_core import _INSTITUTION_CLICK_JS',
      'class FixtureLog:',
      '    def info(self, message): pass',
      'log = FixtureLog()',
      'def is_cloudflare_challenge(title): return title == "challenge"',
      'class PublisherConfig:',
      '    domains = ["sciencedirect.com"]',
      'def detect_publisher(url): return "sciencedirect"',
      'class CARSIClient:',
      '    _login_lock = threading.Lock()',
      '    def __init__(self, config):',
      '        self.config = config',
      '        self._publisher_configs = {"sciencedirect": PublisherConfig()}',
      '    def download_via_browser(self, doi, article_url, output_path): return {"url": article_url}',
      '    def cancellation_fixture(self, page):',
      '        if True:',
      '            if True:',
      '                if True:',
      '                    for _cf_wait in range(12):',
      '                        if is_cloudflare_challenge(page.title() or ""):',
      '                            pass',
      '    def cloudflare_navigation_fixture(self, page):',
      '        if True:',
      '            if True:',
      '                if True:',
      '                    for _cf_wait in range(12):',
      '                        title = page.title() or ""',
      '                        if is_cloudflare_challenge(title):',
      '                            log.info(f"   [CARSI-Browser] Cloudflare challenge detected, waiting... ({_cf_wait+1}/12)")',
      '                            time.sleep(5)',
      '                        else:',
      '                            break',
      '                    else:',
      '                        log.info("   [CARSI-Browser] Cloudflare challenge did not resolve")',
      '        return "continued"',
      '    def institutional_access_fixture(self, page, publisher, has_cookies, needs_login, idp_en):',
      '        if True:',
      '            if True:',
      '                if True:',
      '                    cookies_valid = False',
      '                    if has_cookies and not needs_login:',
      '                        probe_ok = page.evaluate("pdfft probe")',
      '                        cookies_valid = bool(probe_ok)',
      '        return cookies_valid',
      '    def login_cancellation_fixture(self):',
      '        if True:',
      '            if True:',
      '                if True:',
      '                    if True:',
      '                        if True:',
      '                            for i in range(100):',
      '                                time.sleep(3)',
      '    def exact_selection_fixture(self, search_input, page, idp_en):',
      '        if True:',
      '            if True:',
      '                if True:',
      '                    if True:',
      '                        if search_input:',
      '                            clicked = page.evaluate(_INSTITUTION_CLICK_JS, idp_en)',
      '                            if clicked:',
      '                                log.info(f"   [CARSI-Browser] Selected: {clicked}")',
      '                                time.sleep(5)',
      '                            else:',
      '                                search_input.press("Enter")',
      '                                time.sleep(3)',
      '                        else:',
      '                            log.info("   [CARSI-Browser] No institution search box found")',
      '        return "continued"',
      '',
    ].join('\n'));
    await writeFile(join(sources, 'instsci.py'), [
      'import requests',
      'import time',
      'def _get_webvpn_base(config): return "https://webvpn.example"',
      'def convert_url(url, base, config): return base + "/fixture"',
      'def _load_cookies(config): return {"session": "fixture"}',
      'def _get_socks5_proxy(config):',
      '    proxy = config.get("network_proxy", "").strip()',
      '    return proxy if proxy.lower().startswith("socks5://") else ""',
      'def session_status(config):',
      '    jar = _load_cookies(config)',
      '    if not jar:',
      '        return "none"',
      '    base = _get_webvpn_base(config)',
      '    if not base:',
      '        return "none"',
      '    from ..network import USER_AGENT',
      '    test_url = convert_url("https://www.nature.com", base, config)',
      '    try:',
      '        s = requests.Session()',
      '        s.trust_env = False',
      '        s.cookies.update(jar)',
      '        resp = s.get(test_url, timeout=15, allow_redirects=True,',
      '                     headers={"User-Agent": USER_AGENT})',
      '        if "cas" in resp.url.lower() or "login" in resp.url.lower():',
      '            return "expired"',
      '        return "valid" if resp.status_code == 200 else "unreachable"',
      '    except Exception:',
      '        return "unreachable"',
      'def _fetch_via_webvpn(url: str, config: dict, *, stream: bool = False):',
      '    from ..network import USER_AGENT, request_timeout',
      '    base = _get_webvpn_base(config)',
      '    proxied = convert_url(url, base, config)',
      '',
      '    s = requests.Session()',
      '    s.trust_env = False',
      '    s.headers.update({"User-Agent": USER_AGENT})',
      '    s.cookies.update(_load_cookies(config))',
      '',
      '    # Use SOCKS5 proxy if configured (for campus connectors like EasyConnect/aTrust)',
      '    socks5 = _get_socks5_proxy(config)',
      '    if socks5:',
      '        s.proxies = {"http": socks5, "https": socks5}',
      '        s.verify = False  # Campus connectors often use self-signed certs',
      '',
      '    return s.get(proxied, timeout=request_timeout(config), allow_redirects=True, stream=stream)',
      'def browser_login_fixture(config, page):',
      '    if True:',
      '        if True:',
      '            for i in range(100):',
      '                time.sleep(3)',
      '                try:',
      '                    title = page.title()',
      '                except Exception:',
      '                    return None',
      '    return title',
      'def _resolve_doi_url(doi):',
      '    if doi == "query": return "https://linkinghub.elsevier.com/retrieve/pii/QUERY?via=resolver#article"',
      '    if doi == "other": return "https://linkinghub.elsevier.com/other/path?via=resolver#article"',
      '    return "https://linkinghub.elsevier.com/retrieve/pii/S0375960125006267"',
      '',
    ].join('\n'));
    await writeFile(join(sources, 'carsi_source.py'), [
      'from pathlib import Path',
      'from typing import Any',
      'from ..log import get_logger',
      'log = get_logger()',
      'def try_carsi(doi: str, output_path: Path, config: dict[str, Any]) -> dict[str, Any] | None:',
      '    if True:',
      '        from .carsi import CARSIClient, detect_publisher',
      '        from .instsci import _resolve_doi_url',
      '        resolved_url = _resolve_doi_url(doi)',
      '        publisher = detect_publisher(resolved_url)',
      '        client = CARSIClient(config)',
      '        from urllib.parse import urlparse',
      '        cfg = client._publisher_configs.get(publisher)',
      '        if cfg:',
      '            resolved_host = urlparse(resolved_url).hostname or ""',
      '            primary_domain = cfg.domains[0]',
      '            if resolved_host and primary_domain not in resolved_host:',
      '                # Reconstruct URL using primary domain + same path',
      '                from urllib.parse import urlunparse',
      '                parsed = urlparse(resolved_url)',
      '                resolved_url = urlunparse(parsed._replace(',
      '                    scheme="https", netloc=primary_domain))',
      '                log.info(f"   [CARSI] Redirected to primary domain: {resolved_url[:80]}")',
      '        return client.download_via_browser(doi, resolved_url, output_path)',
      '',
    ].join('\n'));
    await writeFile(join(packageRoot, 'server.py'), [
      'mcp_app = FastMCP(',
      '    name="scansci-pdf",',
      '    instructions=("fixture"),',
      ')',
      '',
    ].join('\n'));
    await writeFile(join(packageRoot, 'mcp_server.py'), [
      'mcp = FastMCP("scansci-pdf")',
      '',
    ].join('\n'));

    const patched = runPython([patcher, packageRoot]);
    assert.equal(patched.status, 0, patched.stderr || patched.stdout);
    assert.match(await readFile(join(packageRoot, 'server.py'), 'utf8'), /name="scansci-pdf",\r?\n {4}version="1\.13\.1",/);
    assert.match(await readFile(join(packageRoot, 'mcp_server.py'), 'utf8'), /FastMCP\("scansci-pdf", version="1\.13\.1"\)/);

    const sessionFile = join(root, 'session.netscape');
    await writeFile(sessionFile, 'fixture-session');
    const legacyCache = join(root, 'legacy-cache');
    await mkdir(legacyCache);
    await writeFile(join(legacyCache, 'publisher_cookies.json'), JSON.stringify([
      { name: 'institution', value: 'stale', domain: 'EXAMPLE', path: '', expires: 0 },
    ]));

    const proxyProbe = [
      'import os, runpy, sys',
      'runpy.run_path(sys.argv[1])',
      'print(os.environ.get("NO_PROXY", ""))',
    ].join(';');
    const explicit = runPython(['-c', proxyProbe, join(packageRoot, '__init__.py')], {
      ...process.env,
      SCANSCI_PDF_PROXY: 'http://controlled-proxy:7891',
      HTTP_PROXY: 'http://controlled-proxy:7891',
      HTTPS_PROXY: 'http://controlled-proxy:7891',
      NO_PROXY: 'localhost,127.0.0.1',
      no_proxy: 'localhost,127.0.0.1',
    });
    assert.equal(explicit.status, 0, explicit.stderr);
    assert.equal(explicit.stdout.trim(), 'localhost,127.0.0.1');

    const fallbackEnv = { ...process.env, NO_PROXY: 'localhost', no_proxy: 'localhost' };
    delete fallbackEnv.SCANSCI_PDF_PROXY;
    const fallback = runPython(['-c', proxyProbe, join(packageRoot, '__init__.py')], fallbackEnv);
    assert.equal(fallback.status, 0, fallback.stderr);
    assert.equal(fallback.stdout.trim(), '*');

    const institutionProbe = [
      'import os, shutil, sys, tempfile, threading',
      'from pathlib import Path',
      'sys.path.insert(0, sys.argv[1])',
      'from scansci_pdf import browser_backend, _publisher_strategies_core',
      'assert _publisher_strategies_core._IDP_MAP["浙江大学"] == "Zhejiang University"',
      'assert "const exact" in _publisher_strategies_core._INSTITUTION_CLICK_JS',
      'assert "startsWith" not in _publisher_strategies_core._INSTITUTION_CLICK_JS',
      'assert "contains" not in _publisher_strategies_core._INSTITUTION_CLICK_JS',
      'publisher_source = Path(_publisher_strategies_core.__file__).read_text(encoding="utf-8")',
      'assert "matched = page.evaluate(_INSTITUTION_CLICK_JS, idp_en)" in publisher_source',
      'assert "if not matched:" in publisher_source',
      'assert "si.press(\'ArrowDown\')" not in publisher_source',
      "assert 'cancel_event = config.get(\"_scansci_cancel_event\")' in publisher_source",
      'assert ".includes(name)" not in publisher_source',
      'assert publisher_source.count("cancel_event = config.get") >= 3',
      'from scansci_pdf import sources as source_module',
      'assert "InstSci" in source_module._BROWSER_SOURCE_LABELS',
      'assert source_module._grace_fixture([(None, "InstSci", "Institutional", 60)]) is True',
      'assert "cancel_event.set()" in Path(source_module.__file__).read_text(encoding="utf-8")',
      "assert 'source_config[\"_scansci_cancel_event\"] = cancel_event' in Path(source_module.__file__).read_text(encoding=\"utf-8\")",
      'called = []',
      'cancelled = threading.Event()',
      'source_module._browser_semaphore = threading.Semaphore(0)',
      'thread = threading.Thread(target=lambda: source_module._try_source(lambda *args: called.append(True), "doi", None, {"_scansci_cancel_event": cancelled}, "CARSI"), daemon=True)',
      'thread.start()',
      'cancelled.set()',
      'thread.join(0.5)',
      'assert not thread.is_alive()',
      'assert called == []',
      'inst_called = []',
      'inst_cancelled = threading.Event()',
      'inst_thread = threading.Thread(target=lambda: source_module._try_source(lambda *args: inst_called.append(True), "doi", None, {"_scansci_cancel_event": inst_cancelled}, "InstSci"), daemon=True)',
      'inst_thread.start()',
      'inst_cancelled.set()',
      'inst_thread.join(0.5)',
      'assert not inst_thread.is_alive()',
      'assert inst_called == []',
      'source_set = [(None, "CARSI", "Institutional", 60), (None, "InstSci", "Institutional", 60)]',
      'paths_one = source_module._request_output_paths(source_set, Path(tempfile.gettempdir()), "10.1/test")',
      'paths_two = source_module._request_output_paths(source_set, Path(tempfile.gettempdir()), "10.1/test")',
      'assert {path.name for path in paths_one}.isdisjoint({path.name for path in paths_two})',
      'single_set = [(None, "CARSI", "Institutional", 60)]',
      'single_one = source_module._request_output_paths(single_set, Path(tempfile.gettempdir()), "10.1/test")',
      'single_two = source_module._request_output_paths(single_set, Path(tempfile.gettempdir()), "10.1/test")',
      'assert single_one[0].name != single_two[0].name',
      'source_text = Path(source_module.__file__).read_text(encoding="utf-8")',
      'assert "request_token = uuid.uuid4().hex" in source_text',
      'carsi_text = Path(source_module.__file__).with_name("carsi.py").read_text(encoding="utf-8")',
      "assert 'search_input.press(\"Enter\")' not in carsi_text",
      'assert "Exact institution not found" in carsi_text',
      'class Input:',
      '    def __init__(self): self.pressed = []',
      '    def fill(self, value): self.value = value',
      '    def press(self, key): self.pressed.append(key)',
      'class Page:',
      '    def __init__(self, matched): self.matched = matched; self.input = Input(); self.scripts = []',
      '    def query_selector(self, selector): return self.input',
      '    def evaluate(self, script, arg): self.scripts.append(script); return self.matched',
      '    def title(self): return "auth"',
      '    @property',
      '    def url(self): return "auth"',
      'class NavigationPage:',
      '    def __init__(self): self.titles = ["challenge", "article"]; self.waits = []; self.ready_checks = 0',
      '    def title(self): return self.titles.pop(0) if self.titles else "article"',
      '    @property',
      '    def url(self): return "https://www.sciencedirect.com/science/article/pii/fixture"',
      '    def wait_for_load_state(self, state, timeout):',
      '        self.waits.append((state, timeout))',
      '        if len(self.waits) == 1: raise RuntimeError("navigation replaced context")',
      '    def evaluate(self, script): self.ready_checks += 1; return "complete"',
      'class FailedNavigationPage(NavigationPage):',
      '    def __init__(self): super().__init__(); self.titles = ["article"]',
      '    def wait_for_load_state(self, state, timeout): self.waits.append((state, timeout)); raise RuntimeError("destroyed")',
      'class AccessPage:',
      '    def __init__(self, institution_label, has_pdf, probe_ok): self.institution_label = institution_label; self.has_pdf = has_pdf; self.probe_ok = probe_ok; self.scripts = []',
      '    def evaluate(self, script, arg=None):',
      '        self.scripts.append(script)',
      '        if "#gh-inst-icon-btn.gh-has-institution" in script: return {"label": self.institution_label, "hasPdf": self.has_pdf}',
      '        if "gh-inst-icon-btn" in script: return {"label": "", "hasPdf": False}',
      '        return self.probe_ok',
      '_publisher_strategies_core.time.sleep = lambda _seconds: None',
      'set_cancel = threading.Event()',
      'set_cancel.set()',
      'publisher_page = Page(True)',
      'assert _publisher_strategies_core._fixture_institution_login(publisher_page, "Zhejiang University", {"_scansci_cancel_event": set_cancel}) is False',
      'assert publisher_page.input.pressed == []',
      'publisher_miss = Page(False)',
      'assert _publisher_strategies_core._fixture_institution_login(publisher_miss, "Zhejiang University", {}) is False',
      'assert publisher_miss.input.pressed == []',
      'visible_page = Page(True)',
      'assert _publisher_strategies_core._visible_institutional_fixture(visible_page, "Zhejiang University", {"_scansci_cancel_event": set_cancel}, "Elsevier") is False',
      'assert _publisher_strategies_core._visible_institutional_fixture(Page(False), "Zhejiang University", {}, "Elsevier") is False',
      'assert _publisher_strategies_core._visible_browser_fixture(Page(True), "Zhejiang University", {"_scansci_cancel_event": set_cancel}, "Elsevier") is None',
      'assert _publisher_strategies_core._visible_browser_fixture(Page(False), "Zhejiang University", {}, "Elsevier") is None',
      'headless_scripts = []',
      'assert _publisher_strategies_core._headless_selection_fixture(lambda _tab, script, _config: headless_scripts.append(script) or False, "tab", "Zhejiang University", {}) is False',
      'assert ".includes(name)" not in headless_scripts[0]',
      'from scansci_pdf.sources import carsi as carsi_module',
      'carsi_module.time.sleep = lambda _seconds: None',
      'carsi_client = carsi_module.CARSIClient({"_scansci_cancel_event": set_cancel})',
      'assert carsi_client.cancellation_fixture(Page(False)) is None',
      'assert carsi_client.login_cancellation_fixture() is None',
      'active_client = carsi_module.CARSIClient({})',
      'navigation_page = NavigationPage()',
      'assert active_client.cloudflare_navigation_fixture(navigation_page) == "continued"',
      'assert len(navigation_page.waits) == 4',
      'assert navigation_page.ready_checks == 3',
      'failed_navigation = FailedNavigationPage()',
      'assert active_client.cloudflare_navigation_fixture(failed_navigation) is None',
      'institution_page = AccessPage("Zhejiang University Library", True, False)',
      'assert active_client.institutional_access_fixture(institution_page, "sciencedirect", True, False, "Zhejiang University") is True',
      'assert len(institution_page.scripts) == 1',
      'probe_page = AccessPage("", False, True)',
      'assert active_client.institutional_access_fixture(probe_page, "sciencedirect", True, False, "Zhejiang University") is True',
      'assert len(probe_page.scripts) == 2',
      'no_cookie_page = AccessPage("Zhejiang University Library", True, False)',
      'assert active_client.institutional_access_fixture(no_cookie_page, "sciencedirect", False, False, "Zhejiang University") is False',
      'assert no_cookie_page.scripts == []',
      'login_required_page = AccessPage("Zhejiang University Library", True, False)',
      'assert active_client.institutional_access_fixture(login_required_page, "sciencedirect", True, True, "Zhejiang University") is False',
      'assert login_required_page.scripts == []',
      'wrong_institution_page = AccessPage("Zhejiang University Hospital", True, False)',
      'assert active_client.institutional_access_fixture(wrong_institution_page, "sciencedirect", True, False, "Zhejiang University") is False',
      'assert len(wrong_institution_page.scripts) == 2',
      'other_publisher = AccessPage("Zhejiang University Library", True, False)',
      'assert active_client.institutional_access_fixture(other_publisher, "wiley", True, False, "Zhejiang University") is False',
      'assert len(other_publisher.scripts) == 1',
      'carsi_input = Input()',
      'assert carsi_client.exact_selection_fixture(carsi_input, Page(False), "Zhejiang University") is None',
      'assert carsi_input.pressed == []',
      'assert carsi_client.exact_selection_fixture(None, Page(False), "Zhejiang University") is None',
      'source_module._browser_semaphore = threading.Semaphore(1)',
      'active_cancel = threading.Event()',
      'active_started = threading.Event()',
      'late_path = Path(tempfile.mkdtemp()) / "late.pdf"',
      'def late_source(*args):',
      '    active_started.set()',
      '    active_cancel.wait(0.5)',
      '    late_path.write_bytes(b"%PDF-late")',
      '    return {"success": True, "file": str(late_path)}',
      'worker = source_module._race_worker_fixture(active_cancel, "doi", {}, False)',
      'worker_result = []',
      'active_thread = threading.Thread(target=lambda: worker_result.append(worker(late_source, "CARSI", late_path)), daemon=True)',
      'active_thread.start()',
      'assert active_started.wait(0.5)',
      'active_cancel.set()',
      'active_thread.join(0.5)',
      'assert not active_thread.is_alive()',
      'assert worker_result == [None]',
      'from scansci_pdf import browser_login',
      'login_context = browser_login.Context()',
      'assert browser_login._restore_imported_session_cookies(login_context, {}) == 1',
      'assert [(cookie["name"], cookie["domain"]) for cookie in login_context.added] == [("institution", ".example")]',
      'assert "_restore_imported_session_cookies(context, config)" in Path(browser_login.__file__).read_text(encoding="utf-8")',
      'from scansci_pdf.institutional.publisher_batch import PublisherBatchDownloader',
      'batch_cancel = threading.Event()',
      'batch_cancel.set()',
      'batch = PublisherBatchDownloader({"_scansci_cancel_event": batch_cancel})',
      'batch_page = type("BatchPage", (), {"url": "challenge"})()',
      'batch_result = object()',
      'assert batch._complete_login_from_current_page(batch_page, batch_result) is False',
      'assert batch._wait_for_challenge(batch_page, batch_result) is False',
      'from scansci_pdf.sources import instsci as instsci_module',
      'class ProbeCookies:',
      '    def update(self, values): self.values = values',
      'class ProbeResponse:',
      '    def __init__(self, url, status_code): self.url = url; self.status_code = status_code',
      'class ProbeSession:',
      '    created = []',
      '    next_response = None',
      '    def __init__(self):',
      '        self.trust_env = True; self.headers = {}; self.cookies = ProbeCookies(); self.proxies = {}; self.verify = True',
      '        self.__class__.created.append(self)',
      '    def get(self, url, **kwargs): return self.__class__.next_response or {"url": url, "kwargs": kwargs}',
      'instsci_module.requests.Session = ProbeSession',
      'instsci_module._fetch_via_webvpn("https://publisher.example/article", {"network_proxy": "http://controlled-proxy:7891"})',
      'http_session = ProbeSession.created[-1]',
      'assert http_session.trust_env is False',
      'assert http_session.proxies == {"http": "http://controlled-proxy:7891", "https": "http://controlled-proxy:7891"}',
      'assert http_session.verify is True',
      'instsci_module._fetch_via_webvpn("https://publisher.example/article", {"network_proxy": "socks5://campus-proxy:1080"})',
      'socks_session = ProbeSession.created[-1]',
      'assert socks_session.proxies == {"http": "socks5://campus-proxy:1080", "https": "socks5://campus-proxy:1080"}',
      'assert socks_session.verify is True',
      'ProbeSession.next_response = ProbeResponse("https://webvpn.example/fixture", 200)',
      'assert instsci_module.session_status({"network_proxy": "http://controlled-proxy:7891"}) == "valid"',
      'status_session = ProbeSession.created[-1]',
      'assert status_session.proxies == {"http": "http://controlled-proxy:7891", "https": "http://controlled-proxy:7891"}',
      'assert status_session.verify is True',
      'ProbeSession.next_response = ProbeResponse("https://webvpn.example/cas/login", 200)',
      'assert instsci_module.session_status({"network_proxy": "http://controlled-proxy:7891"}) == "expired"',
      'ProbeSession.next_response = None',
      'instsci_module.time.sleep = lambda _seconds: None',
      'assert instsci_module.browser_login_fixture({"_scansci_cancel_event": batch_cancel}, batch_page) is None',
      'assert not late_path.exists()',
      'late_path.parent.rmdir()',
      'class Future:',
      '    def done(self): return False',
      'class Pool:',
      '    calls = []',
      '    def shutdown(self, **kwargs): self.calls.append(kwargs)',
      'wait_calls = []',
      'source_module.wait_futures = lambda futures, timeout: wait_calls.append((list(futures), timeout))',
      'cleanup_cancel = threading.Event()',
      'pool = Pool()',
      'browser_future = Future()',
      'source_module._race_cleanup_fixture({browser_future: ("CARSI", late_path)}, pool, cleanup_cancel, None)',
      'assert cleanup_cancel.is_set()',
      'assert wait_calls == [([browser_future], 70)]',
      'assert pool.calls == [{"wait": False, "cancel_futures": True}]',
      'from scansci_pdf.sources.carsi import CARSIClient',
      'carsi_source = Path(sys.argv[1]) / "scansci_pdf" / "sources" / "carsi.py"',
      'carsi_text = carsi_source.read_text(encoding="utf-8")',
      'assert carsi_text.count("_scansci_cancel_event") >= 2',
      'controlled = {"server": "http://controlled-proxy:7891"}',
      'assert browser_backend.launch() == controlled',
      'assert browser_backend.launch_persistent_context("/profile") == controlled',
      'assert browser_backend.launch(proxy={}) == controlled',
      'explicit = {"server": "http://explicit-proxy:8000"}',
      'assert browser_backend.launch(proxy=explicit) == explicit',
      'class Context:',
      '    cookies = None',
      '    def add_cookies(self, cookies): self.cookies = cookies',
      'context = Context()',
      '_publisher_strategies_core._restore_cookies_to_context(context, {"cache_dir": sys.argv[2]})',
      'assert context.cookies == [{"name": "institution", "value": "ok", "domain": ".example", "path": "/"}]',
      'from scansci_pdf import browser_engine',
      'assert hasattr(browser_engine, "_linux_descendant_processes")',
      'proc_root = Path(tempfile.mkdtemp())',
      'try:',
      '    for pid, children in ((100, "101 102"), (101, "103"), (102, ""), (103, "")):',
      '        child_file = proc_root / str(pid) / "task" / str(pid) / "children"',
      '        child_file.parent.mkdir(parents=True)',
      '        child_file.write_text(children)',
      '        stat_fields = " ".join(["S"] + ["0"] * 18 + [str(pid * 10)])',
      '        (proc_root / str(pid) / "stat").write_text(f"{pid} (fixture process) {stat_fields}")',
      '    assert browser_engine._linux_process_starttime(100, proc_root) == "1000"',
      '    assert browser_engine._linux_descendant_processes(100, proc_root) == [(101, "1010"), (102, "1020"), (103, "1030")]',
      'finally:',
      '    shutil.rmtree(proc_root)',
      'real_os = browser_engine.os',
      'real_signal = browser_engine.signal',
      'real_starttime = browser_engine._linux_process_starttime',
      'real_snapshot = browser_engine._snapshot_process_tree',
      'class PosixOs:',
      '    name = "posix"',
      '    kills = []',
      '    @classmethod',
      '    def kill(cls, pid, sig): cls.kills.append(pid)',
      'browser_engine.os = PosixOs',
      'browser_engine.signal = type("PosixSignal", (), {"SIGKILL": 9})',
      'identities = {201: "a", 202: "b"}',
      'browser_engine._linux_process_starttime = lambda pid: identities.get(pid)',
      'tree_proc = browser_engine.FixtureProc(returncode=0)',
      'try:',
      '    browser_engine._tree_kill(tree_proc, ("root", [(201, "a"), (202, "b")]))',
      '    assert PosixOs.kills == [202, 201]',
      '    assert not tree_proc.killed',
      '    PosixOs.kills.clear()',
      '    identities[201] = "reused"',
      '    browser_engine._tree_kill(tree_proc, ("root", [(201, "a"), (202, "b")]))',
      '    assert PosixOs.kills == [202]',
      '    PosixOs.kills.clear()',
      '    identities.clear()',
      '    identities[301] = "owned"',
      '    browser_engine._snapshot_process_tree = lambda proc: ("driver", [(301, "owned")])',
      '    _publisher_strategies_core.created.clear()',
      '    _publisher_strategies_core.scenario = "successful_close"',
      '    with _publisher_strategies_core._visible_browser({}, "sciencedirect"):',
      '        pass',
      '    assert PosixOs.kills == [301]',
      'finally:',
      '    browser_engine.os = real_os',
      '    browser_engine.signal = real_signal',
      '    browser_engine._linux_process_starttime = real_starttime',
      '    browser_engine._snapshot_process_tree = real_snapshot',
      '    _publisher_strategies_core.scenario = "happy"',
      'def terminated(proc):',
      '    if os.name == "nt":',
      '        return any(str(proc.pid) in call[0][0] for call in browser_engine.subprocess.calls)',
      '    return proc.killed',
      '_publisher_strategies_core.created.clear()',
      'with _publisher_strategies_core._visible_browser({}, "sciencedirect"):',
      '    pass',
      'assert len(_publisher_strategies_core.created) == 1',
      'assert all(terminated(owner.proc) for owner in _publisher_strategies_core.created)',
      '_publisher_strategies_core.created.clear()',
      '_publisher_strategies_core.scenario = "persistent_page_fail"',
      'with _publisher_strategies_core._visible_browser({}, "sciencedirect"):',
      '    pass',
      'assert len(_publisher_strategies_core.created) == 2',
      'assert all(terminated(owner.proc) for owner in _publisher_strategies_core.created)',
      '_publisher_strategies_core.created.clear()',
      '_publisher_strategies_core.scenario = "fallback_context_fail"',
      'try:',
      '    with _publisher_strategies_core._visible_browser({}, "sciencedirect"):',
      '        pass',
      'except RuntimeError:',
      '    pass',
      'else:',
      '    raise AssertionError("fallback setup failure was not propagated")',
      'assert len(_publisher_strategies_core.created) == 2',
      'assert all(terminated(owner.proc) for owner in _publisher_strategies_core.created)',
      'assert len(browser_backend.os.environ.get("SCANSCI_PDF_PROXY", "")) > 0',
      'async_live = browser_engine.FixtureProc()',
      'browser_engine._tree_kill(async_live)',
      'assert terminated(async_live)',
      'async_exited = browser_engine.FixtureProc(returncode=0)',
      'browser_engine._tree_kill(async_exited)',
      'assert not terminated(async_exited)',
      'class PopenProc(browser_engine.FixtureProc):',
      '    def poll(self): return self.returncode',
      'popen_live = PopenProc()',
      'browser_engine._tree_kill(popen_live)',
      'assert terminated(popen_live)',
      'popen_exited = PopenProc(returncode=0)',
      'browser_engine._tree_kill(popen_exited)',
      'assert not terminated(popen_exited)',
      'from scansci_pdf.sources.carsi_source import try_carsi',
      'result = try_carsi("10.1016/j.physleta.2025.130846", None, {})',
      'assert result["url"] == "https://sciencedirect.com/science/article/pii/S0375960125006267"',
      'query_result = try_carsi("query", None, {})',
      'assert query_result["url"] == "https://sciencedirect.com/science/article/pii/QUERY?via=resolver#article"',
      'other_result = try_carsi("other", None, {})',
      'assert other_result["url"] == "https://sciencedirect.com/other/path?via=resolver#article"',
    ].join('\n');
    const institution = runPython(['-c', institutionProbe, root, legacyCache], {
      ...process.env,
      SCANSCI_PDF_PROXY: 'http://controlled-proxy:7891',
      SCANSCI_PDF_SESSION_FILE: sessionFile,
    });
    assert.equal(institution.status, 0, institution.stderr || institution.stdout);

    const selectionScript = runPython([
      '-c',
      'import json,sys;sys.path.insert(0,sys.argv[1]);from scansci_pdf._publisher_strategies_core import _INSTITUTION_CLICK_JS;print(json.dumps(_INSTITUTION_CLICK_JS))',
      root,
    ]);
    assert.equal(selectionScript.status, 0, selectionScript.stderr || selectionScript.stdout);
    const selectInstitution = Function('document', `return (${JSON.parse(selectionScript.stdout)})`);
    const candidate = (text) => ({
      textContent: text,
      offsetParent: {},
      clicked: false,
      click() { this.clicked = true; },
    });
    const hospital = candidate('Zhejiang University School of Medicine Sir Run Run Shaw Hospital');
    const university = candidate('Zhejiang University');
    const exactDocument = { querySelectorAll: () => [hospital, university] };
    assert.equal(selectInstitution(exactDocument)('Zhejiang University'), 'Zhejiang University');
    assert.equal(hospital.clicked, false);
    assert.equal(university.clicked, true);
    const bilingualUniversity = candidate('浙江大学(Zhejiang University)');
    const bilingualDocument = {
      querySelectorAll: (selector) => selector.includes('[role="option"]')
        ? [hospital, bilingualUniversity]
        : [],
    };
    assert.equal(
      selectInstitution(bilingualDocument)('Zhejiang University'),
      '浙江大学(Zhejiang University)',
    );
    const libraryUniversity = candidate('浙江大学(Zhejiang University) (Zhejiang University Library)');
    const currentElsevierDocument = {
      querySelectorAll: () => [hospital, libraryUniversity],
    };
    assert.equal(
      selectInstitution(currentElsevierDocument)('Zhejiang University'),
      '浙江大学(Zhejiang University) (Zhejiang University Library)',
    );
    assert.equal(hospital.clicked, false);
    assert.equal(bilingualUniversity.clicked, true);
    const ambiguousHospital = candidate('Zhejiang University School of Medicine Sir Run Run Shaw Hospital');
    const ambiguousDocument = { querySelectorAll: () => [ambiguousHospital] };
    assert.equal(selectInstitution(ambiguousDocument)('Zhejiang University'), null);
    assert.equal(ambiguousHospital.clicked, false);

    const lifecycleProbe = [
      'import sys',
      'sys.path.insert(0, sys.argv[1])',
      'from scansci_pdf import browser_engine',
      'from scansci_pdf import sources',
      'class Transport: _proc = browser_engine.FixtureProc()',
      'class Connection: _transport = Transport()',
      'class Impl: _connection = Connection()',
      'class Browser:',
      '    _impl_obj = Impl()',
      '    def close(self): raise RuntimeError("fixture close failure")',
      'class Sem:',
      '    released = 0',
      '    def release(self): self.released += 1',
      'sem = Sem()',
      'browser_engine._tls.browser = Browser()',
      'assert sources.exercise(True, sem) == "ok"',
      'proc = Browser._impl_obj._connection._transport._proc',
      'if browser_engine.os.name == "nt":',
      '    assert any(str(proc.pid) in call[0][0] for call in browser_engine.subprocess.calls)',
      'else:',
      '    assert proc.killed',
      'assert browser_engine._tls.browser is None',
      'assert browser_engine._tls.context is None',
      'assert browser_engine._tls.owned_loop is None',
      'assert sem.released == 1',
      'assert sources.exercise(False, sem) == "ok"',
      'assert sem.released == 2',
    ].join('\n');
    const lifecycle = runPython(['-c', lifecycleProbe, root]);
    assert.equal(lifecycle.status, 0, lifecycle.stderr || lifecycle.stdout);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});
