import assert from 'node:assert/strict';
import { mkdtemp, mkdir, rm, writeFile } from 'node:fs/promises';
import { spawnSync } from 'node:child_process';
import { join, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import process from 'node:process';
import test from 'node:test';

const patcher = resolve(import.meta.dirname, '..', 'patch-upstream.py');
const python = process.platform === 'win32' ? 'python' : 'python3';

function runPython(args, env = process.env) {
  return spawnSync(python, args, { encoding: 'utf8', env });
}

test('upstream patch connects the controlled institutional context and reaps browser workers', async () => {
  const root = await mkdtemp(join(tmpdir(), 'scansci-upstream-patch-'));
  const packageRoot = join(root, 'scansci_pdf');
  const sources = join(packageRoot, 'sources');
  try {
    await mkdir(sources, { recursive: true });
    await writeFile(join(packageRoot, 'log.py'), [
      'class Log:',
      '    def info(self, message): pass',
      'def get_logger(): return Log()',
      '',
    ].join('\n'));
    await writeFile(join(packageRoot, '__init__.py'), [
      'import os as _os',
      '_os.environ["NO_PROXY"] = "*"',
      '_os.environ["no_proxy"] = "*"',
      '',
    ].join('\n'));
    await writeFile(join(packageRoot, '_publisher_strategies_core.py'), [
      'from __future__ import annotations',
      'import contextlib',
      'import json',
      'import re',
      'import threading',
      'import time',
      'from pathlib import Path',
      'from typing import Any',
      'def _restore_cookies_to_context(context: Any, config: dict[str, Any]) -> None:',
      '    try:',
      '        from .browser_cookies import load_saved_cookies',
      '        saved = load_saved_cookies(config)',
      '        if saved:',
      '            pw_cookies = []',
      '            for c in saved:',
      '                pw_c = {"name": c.get("name", ""), "value": c.get("value", ""),',
      '                         "domain": c.get("domain", ""), "path": c.get("path", "/")}',
      '                if pw_c["domain"]:',
      '                    pw_cookies.append(pw_c)',
      '            if pw_cookies:',
      '                context.add_cookies(pw_cookies)',
      '    except Exception:',
      '        pass',
      'from .browser_engine import FixtureProc',
      'class FixtureTransport:',
      '    def __init__(self, proc): self._proc = proc',
      'class FixtureConnection:',
      '    def __init__(self, proc): self._transport = FixtureTransport(proc)',
      'class FixtureImpl:',
      '    def __init__(self, proc): self._connection = FixtureConnection(proc)',
      'class FixtureContext:',
      '    def __init__(self, fail_new_page=False, proc=None):',
      '        self.proc = proc or FixtureProc()',
      '        self._impl_obj = FixtureImpl(self.proc)',
      '        self.fail_new_page = fail_new_page',
      '    def close(self):',
      '        if scenario == "successful_close":',
      '            self.proc.returncode = 0',
      '            return',
      '        raise RuntimeError("fixture close failure")',
      '    def new_page(self):',
      '        if self.fail_new_page: raise RuntimeError("fixture page failure")',
      '        return None',
      'class FixtureBrowser:',
      '    def __init__(self, fail_new_context=False):',
      '        self.proc = FixtureProc()',
      '        self._impl_obj = FixtureImpl(self.proc)',
      '        self.fail_new_context = fail_new_context',
      '    def close(self): raise RuntimeError("fixture close failure")',
      '    def new_context(self, viewport=None):',
      '        if self.fail_new_context: raise RuntimeError("fixture context failure")',
      '        return FixtureContext(proc=self.proc)',
      '_HAS_CLOAKBROWSER = True',
      'def _get_profile_dir(config, publisher): return Path("/profile")',
      'scenario = "happy"',
      'created = []',
      'def launch_persistent_context(*args, **kwargs):',
      '    ctx = FixtureContext(fail_new_page=scenario in ("persistent_page_fail", "fallback_context_fail"))',
      '    created.append(ctx)',
      '    return ctx',
      'def launch(*args, **kwargs):',
      '    browser = FixtureBrowser(fail_new_context=scenario == "fallback_context_fail")',
      '    created.append(browser)',
      '    return browser',
      'class Log:',
      '    def info(self, message): pass',
      'log = Log()',
      '@contextlib.contextmanager',
      'def _visible_browser(config: dict[str, Any], publisher: str, *, viewport: dict | None = None):',
      '    """Open visible CloakBrowser with persistent profile. Falls back to ephemeral."""',
      '    if not _HAS_CLOAKBROWSER:',
      '        raise RuntimeError("cloakbrowser not installed. Run: pip install cloakbrowser")',
      '    profile_dir = _get_profile_dir(config, publisher)',
      '    browser = None',
      '',
      '    try:',
      '        ctx = launch_persistent_context(',
      '            str(profile_dir),',
      '            headless=False, humanize=True,',
      '            args=["--disable-features=CrossOriginOpenerPolicy"],',
      '        )',
      '        page = ctx.new_page()',
      '        log.info(f"   [{publisher}] persistent browser profile: {profile_dir}")',
      '        # Ensure cookies are loaded from saved file',
      '        _restore_cookies_to_context(ctx, config)',
      '    except Exception as _e:',
      '        log.info(f"   [{publisher}] persistent context unavailable ({_e}), using ephemeral")',
      '        _vp = viewport or {"width": 1440, "height": 900}',
      '        browser = launch(headless=False, humanize=True,',
      '                         args=["--disable-features=CrossOriginOpenerPolicy"])',
      '        ctx = browser.new_context(viewport=_vp)',
      '        _restore_cookies_to_context(ctx, config)',
      '        page = ctx.new_page()',
      '',
      '    try:',
      '        yield ctx, page',
      '    finally:',
      '        try:',
      '            if browser:',
      '                browser.close()',
      '            else:',
      '                ctx.close()',
      '        except Exception:',
      '            pass',
      'def create_tab(url, config, timeout): return "tab"',
      'config = {}',
      'tab_id = create_tab("https://www.google.com/", config, timeout=15.0)',
      '',
    ].join('\n'));
    await writeFile(join(packageRoot, 'browser_engine.py'), [
      'import os',
      'import shutil',
      'import subprocess',
      'from pathlib import Path',
      'from typing import Any',
      'class FixtureSubprocess:',
      '    calls = []',
      '    @classmethod',
      '    def run(cls, *args, **kwargs): cls.calls.append((args, kwargs))',
      'subprocess = FixtureSubprocess',
      'class FixtureProc:',
      '    next_pid = 1000',
      '    def __init__(self, returncode=None):',
      '        self.returncode = returncode',
      '        self.pid = FixtureProc.next_pid',
      '        FixtureProc.next_pid += 1',
      '        self.killed = False',
      '    def kill(self): self.killed = True',
      'class TLS: pass',
      '_tls = TLS()',
      'def _unregister_browser(browser): pass',
      'def _tree_kill(proc: Any) -> None:',
      '    """Force-kill a driver process and its whole child tree (Windows-safe)."""',
      '    if proc is None or proc.poll() is not None:',
      '        return',
      '    if os.name == "nt":',
      '        subprocess.run(',
      '            ["taskkill", "/F", "/T", "/PID", str(proc.pid)],',
      '            capture_output=True, timeout=15,',
      '        )',
      '    else:',
      '        proc.kill()',
      'def configure_context(browser, config):',
      '    proxy = config.get("browser_static_proxy", "")',
      '    context = browser.new_context()',
      '',
      '    # Launching the sync API leaves its dispatcher event loop "running" in',
      '    return context',
      'def _parse_netscape_cookies(text):',
      '    assert text == "fixture-session"',
      '    return [{"name": "institution", "value": "ok", "domain": ".example", "path": "/", "expires": 0}]',
      'def shutdown_shared_browser():',
      '    """Shut down the current thread\'s browser. Call on thread exit or process exit."""',
      '    browser = getattr(_tls, "browser", None)',
      '    if browser is not None:',
      '        try:',
      '            browser.close()',
      '        except Exception:',
      '            pass',
      '        _unregister_browser(browser)',
      '        _tls.browser = None',
      '        _tls.context = None',
      '        logger.info("browser_engine: browser shut down")',
      'class Logger:',
      '    def info(self, message): pass',
      'logger = Logger()',
      '',
    ].join('\n'));
    await writeFile(join(packageRoot, 'browser_backend.py'), [
      'import os',
      'BACKEND_PATCHRIGHT = "patchright"',
      'BACKEND_CAMOUFOX = "camoufox"',
      'def resolve_backend(config): return BACKEND_PATCHRIGHT',
      'def _launch_patchright(config, headless, proxy, args, **kwargs): return proxy',
      'def _launch_patchright_persistent(config, user_data_dir, headless, proxy, args, **kwargs): return proxy',
      '',
      '# ---------------------------------------------------------------------------',
      '# Public entry points',
      '# ---------------------------------------------------------------------------',
      '',
      'def launch(',
      '    *,',
      '    headless: bool = True,',
      '    proxy = None,',
      '    args = None,',
      '    humanize: bool = True,',
      '    config = None,',
      '    **kwargs,',
      '):',
      '    """Launch.',
      '',
      '    ``playwright.chromium.launch()`` / ``cloakbrowser.launch()``.',
      '    """',
      '    backend = resolve_backend(config)',
      '    if backend == BACKEND_PATCHRIGHT:',
      '        return _launch_patchright(config, headless=headless, proxy=proxy, args=args, **kwargs)',
      '',
      'def launch_persistent_context(',
      '    user_data_dir: str,',
      '    *,',
      '    headless: bool = True,',
      '    proxy = None,',
      '    args = None,',
      '    humanize: bool = True,',
      '    config = None,',
      '    **kwargs,',
      '):',
      '    """Persistent context.',
      '',
      '    Same contract as ``playwright.chromium.launch_persistent_context()``.',
      '    """',
      '    backend = resolve_backend(config)',
      '    if backend == BACKEND_PATCHRIGHT:',
      '        return _launch_patchright_persistent(',
      '            config, user_data_dir, headless=headless, proxy=proxy, args=args, **kwargs',
      '        )',
      '',
    ].join('\n'));
    await writeFile(join(packageRoot, 'browser_cookies.py'), [
      'from __future__ import annotations',
      'import json',
      'import time',
      'from pathlib import Path',
      'from typing import Any',
      'def _is_cookie_valid(cookie, now): return not cookie.get("expires") or cookie["expires"] > now',
      'def load_saved_cookies(config: dict[str, Any]) -> list[dict[str, Any]]:',
      '    """Load previously saved publisher cookies, filtering out expired ones."""',
      '    from .config import DATA_DIR',
      '    cookie_file = Path(config.get("cache_dir", str(DATA_DIR / "cache"))) / "publisher_cookies.json"',
      '    if not cookie_file.exists():',
      '        return []',
      '    try:',
      '        cookies = json.loads(cookie_file.read_text(encoding="utf-8"))',
      '    except Exception:',
      '        return []',
      '    now = time.time()',
      '    return [c for c in cookies if _is_cookie_valid(c, now)]',
      '',
    ].join('\n'));
    await writeFile(join(packageRoot, 'config.py'), [
      'from pathlib import Path',
      'DATA_DIR = Path("/unused")',
      '',
    ].join('\n'));
    await writeFile(join(sources, '__init__.py'), [
      'def exercise(is_browser, sem):',
      '    try:',
      '        return "ok"',
      '    finally:',
      '        if sem:',
      '            sem.release()',
      '',
    ].join('\n'));
    await writeFile(join(sources, 'carsi.py'), [
      'class PublisherConfig:',
      '    domains = ["sciencedirect.com"]',
      'def detect_publisher(url): return "sciencedirect"',
      'class CARSIClient:',
      '    def __init__(self, config): self._publisher_configs = {"sciencedirect": PublisherConfig()}',
      '    def download_via_browser(self, doi, article_url, output_path): return {"url": article_url}',
      '',
    ].join('\n'));
    await writeFile(join(sources, 'instsci.py'), [
      'def _resolve_doi_url(doi):',
      '    if doi == "query": return "https://linkinghub.elsevier.com/retrieve/pii/QUERY?via=resolver#article"',
      '    if doi == "other": return "https://linkinghub.elsevier.com/other/path?via=resolver#article"',
      '    return "https://linkinghub.elsevier.com/retrieve/pii/S0375960125006267"',
      '',
    ].join('\n'));
    await writeFile(join(sources, 'carsi_source.py'), [
      'from pathlib import Path',
      'from typing import Any',
      'from ..log import get_logger',
      'log = get_logger()',
      'def try_carsi(doi: str, output_path: Path, config: dict[str, Any]) -> dict[str, Any] | None:',
      '    if True:',
      '        from .carsi import CARSIClient, detect_publisher',
      '        from .instsci import _resolve_doi_url',
      '        resolved_url = _resolve_doi_url(doi)',
      '        publisher = detect_publisher(resolved_url)',
      '        client = CARSIClient(config)',
      '        from urllib.parse import urlparse',
      '        cfg = client._publisher_configs.get(publisher)',
      '        if cfg:',
      '            resolved_host = urlparse(resolved_url).hostname or ""',
      '            primary_domain = cfg.domains[0]',
      '            if resolved_host and primary_domain not in resolved_host:',
      '                # Reconstruct URL using primary domain + same path',
      '                from urllib.parse import urlunparse',
      '                parsed = urlparse(resolved_url)',
      '                resolved_url = urlunparse(parsed._replace(',
      '                    scheme="https", netloc=primary_domain))',
      '                log.info(f"   [CARSI] Redirected to primary domain: {resolved_url[:80]}")',
      '        return client.download_via_browser(doi, resolved_url, output_path)',
      '',
    ].join('\n'));

    const patched = runPython([patcher, packageRoot]);
    assert.equal(patched.status, 0, patched.stderr || patched.stdout);

    const sessionFile = join(root, 'session.netscape');
    await writeFile(sessionFile, 'fixture-session');
    const legacyCache = join(root, 'legacy-cache');
    await mkdir(legacyCache);
    await writeFile(join(legacyCache, 'publisher_cookies.json'), JSON.stringify([
      { name: 'institution', value: 'stale', domain: 'EXAMPLE', path: '', expires: 0 },
    ]));

    const proxyProbe = [
      'import os, runpy, sys',
      'runpy.run_path(sys.argv[1])',
      'print(os.environ.get("NO_PROXY", ""))',
    ].join(';');
    const explicit = runPython(['-c', proxyProbe, join(packageRoot, '__init__.py')], {
      ...process.env,
      SCANSCI_PDF_PROXY: 'http://controlled-proxy:7891',
      HTTP_PROXY: 'http://controlled-proxy:7891',
      HTTPS_PROXY: 'http://controlled-proxy:7891',
      NO_PROXY: 'localhost,127.0.0.1',
      no_proxy: 'localhost,127.0.0.1',
    });
    assert.equal(explicit.status, 0, explicit.stderr);
    assert.equal(explicit.stdout.trim(), 'localhost,127.0.0.1');

    const fallbackEnv = { ...process.env, NO_PROXY: 'localhost', no_proxy: 'localhost' };
    delete fallbackEnv.SCANSCI_PDF_PROXY;
    const fallback = runPython(['-c', proxyProbe, join(packageRoot, '__init__.py')], fallbackEnv);
    assert.equal(fallback.status, 0, fallback.stderr);
    assert.equal(fallback.stdout.trim(), '*');

    const institutionProbe = [
      'import os, shutil, sys, tempfile',
      'from pathlib import Path',
      'sys.path.insert(0, sys.argv[1])',
      'from scansci_pdf import browser_backend, _publisher_strategies_core',
      'controlled = {"server": "http://controlled-proxy:7891"}',
      'assert browser_backend.launch() == controlled',
      'assert browser_backend.launch_persistent_context("/profile") == controlled',
      'assert browser_backend.launch(proxy={}) == controlled',
      'explicit = {"server": "http://explicit-proxy:8000"}',
      'assert browser_backend.launch(proxy=explicit) == explicit',
      'class Context:',
      '    cookies = None',
      '    def add_cookies(self, cookies): self.cookies = cookies',
      'context = Context()',
      '_publisher_strategies_core._restore_cookies_to_context(context, {"cache_dir": sys.argv[2]})',
      'assert context.cookies == [{"name": "institution", "value": "ok", "domain": ".example", "path": "/"}]',
      'from scansci_pdf import browser_engine',
      'assert hasattr(browser_engine, "_linux_descendant_processes")',
      'proc_root = Path(tempfile.mkdtemp())',
      'try:',
      '    for pid, children in ((100, "101 102"), (101, "103"), (102, ""), (103, "")):',
      '        child_file = proc_root / str(pid) / "task" / str(pid) / "children"',
      '        child_file.parent.mkdir(parents=True)',
      '        child_file.write_text(children)',
      '        stat_fields = " ".join(["S"] + ["0"] * 18 + [str(pid * 10)])',
      '        (proc_root / str(pid) / "stat").write_text(f"{pid} (fixture process) {stat_fields}")',
      '    assert browser_engine._linux_process_starttime(100, proc_root) == "1000"',
      '    assert browser_engine._linux_descendant_processes(100, proc_root) == [(101, "1010"), (102, "1020"), (103, "1030")]',
      'finally:',
      '    shutil.rmtree(proc_root)',
      'real_os = browser_engine.os',
      'real_signal = browser_engine.signal',
      'real_starttime = browser_engine._linux_process_starttime',
      'real_snapshot = browser_engine._snapshot_process_tree',
      'class PosixOs:',
      '    name = "posix"',
      '    kills = []',
      '    @classmethod',
      '    def kill(cls, pid, sig): cls.kills.append(pid)',
      'browser_engine.os = PosixOs',
      'browser_engine.signal = type("PosixSignal", (), {"SIGKILL": 9})',
      'identities = {201: "a", 202: "b"}',
      'browser_engine._linux_process_starttime = lambda pid: identities.get(pid)',
      'tree_proc = browser_engine.FixtureProc(returncode=0)',
      'try:',
      '    browser_engine._tree_kill(tree_proc, ("root", [(201, "a"), (202, "b")]))',
      '    assert PosixOs.kills == [202, 201]',
      '    assert not tree_proc.killed',
      '    PosixOs.kills.clear()',
      '    identities[201] = "reused"',
      '    browser_engine._tree_kill(tree_proc, ("root", [(201, "a"), (202, "b")]))',
      '    assert PosixOs.kills == [202]',
      '    PosixOs.kills.clear()',
      '    identities.clear()',
      '    identities[301] = "owned"',
      '    browser_engine._snapshot_process_tree = lambda proc: ("driver", [(301, "owned")])',
      '    _publisher_strategies_core.created.clear()',
      '    _publisher_strategies_core.scenario = "successful_close"',
      '    with _publisher_strategies_core._visible_browser({}, "sciencedirect"):',
      '        pass',
      '    assert PosixOs.kills == [301]',
      'finally:',
      '    browser_engine.os = real_os',
      '    browser_engine.signal = real_signal',
      '    browser_engine._linux_process_starttime = real_starttime',
      '    browser_engine._snapshot_process_tree = real_snapshot',
      '    _publisher_strategies_core.scenario = "happy"',
      'def terminated(proc):',
      '    if os.name == "nt":',
      '        return any(str(proc.pid) in call[0][0] for call in browser_engine.subprocess.calls)',
      '    return proc.killed',
      '_publisher_strategies_core.created.clear()',
      'with _publisher_strategies_core._visible_browser({}, "sciencedirect"):',
      '    pass',
      'assert len(_publisher_strategies_core.created) == 1',
      'assert all(terminated(owner.proc) for owner in _publisher_strategies_core.created)',
      '_publisher_strategies_core.created.clear()',
      '_publisher_strategies_core.scenario = "persistent_page_fail"',
      'with _publisher_strategies_core._visible_browser({}, "sciencedirect"):',
      '    pass',
      'assert len(_publisher_strategies_core.created) == 2',
      'assert all(terminated(owner.proc) for owner in _publisher_strategies_core.created)',
      '_publisher_strategies_core.created.clear()',
      '_publisher_strategies_core.scenario = "fallback_context_fail"',
      'try:',
      '    with _publisher_strategies_core._visible_browser({}, "sciencedirect"):',
      '        pass',
      'except RuntimeError:',
      '    pass',
      'else:',
      '    raise AssertionError("fallback setup failure was not propagated")',
      'assert len(_publisher_strategies_core.created) == 2',
      'assert all(terminated(owner.proc) for owner in _publisher_strategies_core.created)',
      'assert len(browser_backend.os.environ.get("SCANSCI_PDF_PROXY", "")) > 0',
      'async_live = browser_engine.FixtureProc()',
      'browser_engine._tree_kill(async_live)',
      'assert terminated(async_live)',
      'async_exited = browser_engine.FixtureProc(returncode=0)',
      'browser_engine._tree_kill(async_exited)',
      'assert not terminated(async_exited)',
      'class PopenProc(browser_engine.FixtureProc):',
      '    def poll(self): return self.returncode',
      'popen_live = PopenProc()',
      'browser_engine._tree_kill(popen_live)',
      'assert terminated(popen_live)',
      'popen_exited = PopenProc(returncode=0)',
      'browser_engine._tree_kill(popen_exited)',
      'assert not terminated(popen_exited)',
      'from scansci_pdf.sources.carsi_source import try_carsi',
      'result = try_carsi("10.1016/j.physleta.2025.130846", None, {})',
      'assert result["url"] == "https://sciencedirect.com/science/article/pii/S0375960125006267"',
      'query_result = try_carsi("query", None, {})',
      'assert query_result["url"] == "https://sciencedirect.com/science/article/pii/QUERY?via=resolver#article"',
      'other_result = try_carsi("other", None, {})',
      'assert other_result["url"] == "https://sciencedirect.com/other/path?via=resolver#article"',
    ].join('\n');
    const institution = runPython(['-c', institutionProbe, root, legacyCache], {
      ...process.env,
      SCANSCI_PDF_PROXY: 'http://controlled-proxy:7891',
      SCANSCI_PDF_SESSION_FILE: sessionFile,
    });
    assert.equal(institution.status, 0, institution.stderr || institution.stdout);

    const lifecycleProbe = [
      'import sys',
      'sys.path.insert(0, sys.argv[1])',
      'from scansci_pdf import browser_engine',
      'from scansci_pdf import sources',
      'class Transport: _proc = browser_engine.FixtureProc()',
      'class Connection: _transport = Transport()',
      'class Impl: _connection = Connection()',
      'class Browser:',
      '    _impl_obj = Impl()',
      '    def close(self): raise RuntimeError("fixture close failure")',
      'class Sem:',
      '    released = 0',
      '    def release(self): self.released += 1',
      'sem = Sem()',
      'browser_engine._tls.browser = Browser()',
      'assert sources.exercise(True, sem) == "ok"',
      'proc = Browser._impl_obj._connection._transport._proc',
      'if browser_engine.os.name == "nt":',
      '    assert any(str(proc.pid) in call[0][0] for call in browser_engine.subprocess.calls)',
      'else:',
      '    assert proc.killed',
      'assert browser_engine._tls.browser is None',
      'assert browser_engine._tls.context is None',
      'assert browser_engine._tls.owned_loop is None',
      'assert sem.released == 1',
      'assert sources.exercise(False, sem) == "ok"',
      'assert sem.released == 2',
    ].join('\n');
    const lifecycle = runPython(['-c', lifecycleProbe, root]);
    assert.equal(lifecycle.status, 0, lifecycle.stderr || lifecycle.stdout);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});
