import { createHash, randomUUID } from 'node:crypto';
import { chmod, chown, mkdir, open, lstat, readdir, readFile, rename, stat, unlink, utimes } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { SynclipVideoClient, SynclipVideoError, downloadSynclipVideo, validateSynclipVideoTask } from '../../packages/ai-gateway/dist/synclip-video-api.js';

const ROOT='/opt/openscience-synclip-video', UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i, MAX_JSON=512*1024, MAX_PNG=10*1024*1024, MAX_MP4=256*1024*1024, REV='synclip-video-v1';
const fail=code=>{throw Error(code)}; const hash=b=>createHash('sha256').update(b).digest('hex');
async function dir(p){const s=await lstat(p);if(!s.isDirectory()||s.isSymbolicLink())fail('VIDEO_DIR');}
async function read(p,n){const s=await lstat(p);if(!s.isFile()||s.isSymbolicLink()||s.size<=0||s.size>n)fail('VIDEO_FILE');const b=await readFile(p);if(b.length!==s.size)fail('VIDEO_FILE');return b;}
async function write(p,b,m=0o600){const t=p+'.'+randomUUID()+'.tmp',f=await open(t,'wx',m);try{await f.writeFile(b);await f.sync()}finally{await f.close()}await rename(t,p)}
async function exclusive(p,b){try{const f=await open(p,'wx',0o600);try{await f.writeFile(b);await f.sync()}finally{await f.close()}return true}catch(e){if(e.code==='EEXIST')return false;throw e}}
const j=async(p,n=MAX_JSON)=>JSON.parse((await read(p,n)).toString('utf8'));
async function key(p){const s=await lstat(p);if(!s.isFile()||s.isSymbolicLink()||s.uid!==0||(s.mode&511)!==384||resolve(p)!==p)fail('VIDEO_KEY');const v=(await read(p,4096)).toString();if(!/^[\x21-\x7e]{1,4096}$/u.test(v))fail('VIDEO_KEY');return v}
function config(v){if(!v||v.model!=='ltx23'||v.resolution!=='720p'||v.referenceMode!=='inline'||v.adapterRevision!==REV||!/^sha256:[a-f0-9]{64}$/u.test(v.rendererImage)||[v.inbox,v.results,v.privateRoot,v.keyPath].some(p=>typeof p!=='string'||!p.startsWith('/opt/')))fail('VIDEO_CONFIG');return v}
async function request(dirPath,id){const r=await j(join(dirPath,'request.json'));if(r.schemaVersion!==1||r.id!==id||r.taskId!==id||r.profile!=='content-driven-v1'||r.provider!=='synclip'||r.model!=='ltx23'||r.resolution!=='720p'||!UUID.test(id)||!Number.isSafeInteger(r.deadlineAt)||r.deadlineAt<=Date.now()||!Array.isArray(r.scenes)||r.scenes.length<3||r.scenes.length>6||!r.files||!Array.isArray(r.files.scenes))fail('VIDEO_REQUEST');const story=await read(join(dirPath,'storyboard.json'),MAX_JSON);if(r.files.storyboard?.name!=='storyboard.json'||r.files.storyboard.size!==story.length||r.files.storyboard.sha256!==hash(story)||r.files.scenes.length!==r.scenes.length)fail('VIDEO_REQUEST');for(let i=0;i<r.scenes.length;i++){const s=r.scenes[i],spec=r.files.scenes[i],b=await read(join(dirPath,'scene-'+i+'.png'),MAX_PNG);if(s.index!==i||![5,10,15].includes(s.durationSeconds)||typeof s.prompt!=='string'||s.prompt.length<20||spec?.size!==b.length||spec.sha256!==hash(b)||s.image?.sha256!==spec.sha256)fail('VIDEO_REQUEST')}if(hash(Buffer.from(JSON.stringify(r.files)))!==r.inputHash)fail('VIDEO_REQUEST');return r}
async function ffmpeg(cfg,privateDir,outDir){await mkdir(outDir,{recursive:true,mode:0o700});return new Promise((ok,bad)=>{const p=spawn('docker',['run','--rm','--network','none','--read-only','--cap-drop','ALL','--security-opt','no-new-privileges','--memory','1g','--memory-swap','1g','--cpus','2','--pids-limit','128','--tmpfs','/tmp:rw,noexec,nosuid,nodev,size=256m','-v',privateDir+':/input:ro','-v',outDir+':/output:rw','--entrypoint','/usr/bin/ffmpeg',cfg.rendererImage,'-hide_banner','-loglevel','error','-f','concat','-safe','0','-i','/input/concat.txt','-c:v','libx264','-preset','medium','-crf','18','-pix_fmt','yuv420p','-c:a','aac','-b:a','128k','-movflags','+faststart','/output/result.mp4'],{stdio:['ignore','ignore','ignore']});p.once('error',bad);p.once('exit',c=>c===0?ok():bad(Error('VIDEO_RENDER')))});}
async function publish(cfg,r,status,error,output){const d=join(cfg.results,r.id);await mkdir(d,{recursive:true,mode:0o750});const v={schemaVersion:1,id:r.id,inputHash:r.inputHash,executionAttempt:r.executionAttempt,provider:'synclip',model:'ltx23',adapterRevision:REV,status,...(error?{errorCode:error}:{}),...(output?output.result:{})};if(output){await write(join(d,'result.mp4'),output.bytes,0o640);await write(join(d,'metrics.json'),JSON.stringify(output.metrics),0o640)}await write(join(d,'result.json'),JSON.stringify(v),0o640)}
async function execute(cfg,d,r,apiKey){const c=new SynclipVideoClient({apiKey,timeoutMs:15000}),shots=join(d,'shots'),rp=join(d,'synclip-receipts.json');await mkdir(shots,{recursive:true,mode:0o700});let receipt={id:r.id,shots:[]};try{receipt=await j(rp)}catch(e){if(e.code!=='ENOENT')throw e}for(const s of r.scenes){const old=receipt.shots.find(x=>x.index===s.index),out=join(shots,'shot-'+s.index+'.mp4');if(old&&await stat(out).then(()=>true).catch(()=>false))continue;if(!old){const ap=join(d,'shot-'+s.index+'.attempt.json');if(await stat(ap).then(()=>true).catch(()=>false)||!await exclusive(ap,JSON.stringify({id:r.id,index:s.index,inputHash:r.inputHash})))throw Error('UNCERTAIN');try{const frame=(await read(join(d,'scene-'+s.index+'.png'),MAX_PNG)).toString('base64');const made=await c.create({prompt:s.prompt,model:'ltx23',duration:s.durationSeconds,resolution:'720p',first_frame_url:'data:image/png;base64,'+frame});receipt={...receipt,shots:[...receipt.shots,{index:s.index,taskId:made.task_id}]};await write(rp,JSON.stringify(receipt));await unlink(ap)}catch(e){if(e instanceof SynclipVideoError&&e.outcome==='rejected')await unlink(ap).catch(()=>{});throw e}}const task=receipt.shots.find(x=>x.index===s.index);if(!task)fail('VIDEO_RECEIPT');for(;;){if(Date.now()>=r.deadlineAt)throw Error('DEADLINE_EXCEEDED');const t=validateSynclipVideoTask(await c.query(task.taskId),task.taskId);await write(join(d,'shot-'+s.index+'.status.json'),JSON.stringify(t));if(t.status==='failed')throw Error('PROVIDER_FAILED');if(t.status==='completed'){await write(out,await downloadSynclipVideo(t,{timeoutMs:90000}));break}await new Promise(x=>setTimeout(x,3000))}}await write(join(d,'concat.txt'),r.scenes.map(s=>"file '/input/shots/shot-"+s.index+".mp4'").join('\n')+'\n');const outDir=join(d,'output');await ffmpeg(cfg,d,outDir);const bytes=await read(join(outDir,'result.mp4'),MAX_MP4);if(!bytes.subarray(4,12).includes(Buffer.from('ftyp')))fail('VIDEO_MP4');await publish(cfg,r,'succeeded',undefined,{bytes,metrics:{provider:'synclip',model:'ltx23',shotCount:r.scenes.length,audioMode:'provider-output-unverified'},result:{contentType:'video/mp4',outputSha256:hash(bytes),outputSize:bytes.length}})}
export async function runSynclipVideoBrokerOnce(cfg,deps={}){for(const p of[cfg.inbox,cfg.results,cfg.privateRoot])await dir(p);const ids=[...(await readdir(cfg.inbox)).filter(x=>UUID.test(x)),...(await readdir(cfg.privateRoot)).filter(x=>UUID.test(x))];for(const id of [...new Set(ids)].sort()){const src=join(cfg.inbox,id),d=join(cfg.privateRoot,id);if(!await stat(d).then(()=>true).catch(()=>false))await rename(src,d);const r=await request(d,id),done=join(cfg.results,id,'result.json');if(await stat(done).then(()=>true).catch(()=>false))continue;const started=join(d,'started'),has=await stat(started).then(()=>true).catch(()=>false),rec=join(d,'synclip-receipts.json');if(has&&!await stat(rec).then(()=>true).catch(()=>false)){await publish(cfg,r,'uncertain','UNCERTAIN');return{id,status:'uncertain'}}if(!has)await exclusive(started,String(Date.now()));try{await execute(cfg,d,r,await(deps.readKey??key)(cfg.keyPath));return{id,status:'succeeded'}}catch(e){const code=e?.message==='DEADLINE_EXCEEDED'?'DEADLINE_EXCEEDED':e instanceof SynclipVideoError&&e.outcome==='rejected'?'PROVIDER_REJECTED':e?.message==='UNCERTAIN'?'UNCERTAIN':'EXECUTION_FAILED';await publish(cfg,r,code==='UNCERTAIN'?'uncertain':'failed',code);return{id,status:code==='UNCERTAIN'?'uncertain':'failed'}}}return null}
export function validateSynclipVideoBrokerConfig(v){return config(v)}
async function main(){if(process.getuid?.()!==0||process.getgid?.()!==1000||process.argv.length!==4||process.argv[2]!=='--config'||resolve(process.argv[3])!==ROOT+'/config.json')throw Error('VIDEO_CONFIG_REQUIRED');const p=resolve(process.argv[3]),s=await lstat(p);if(!s.isFile()||s.isSymbolicLink()||s.uid!==0||(s.mode&511)!==384)throw Error('VIDEO_CONFIG_PERMISSIONS');const cfg=config(JSON.parse((await read(p,16384)).toString()));for(const x of[cfg.inbox,cfg.results,cfg.privateRoot])await dir(x);await key(cfg.keyPath);const ready=join(cfg.results,'.ready'),beat=async accepting=>{await write(ready,JSON.stringify({schemaVersion:1,provider:'synclip',model:'ltx23',updatedAt:Date.now(),accepting}));await chown(ready,0,1000);await chmod(ready,0o640)};await beat(true);try{const v=await runSynclipVideoBrokerOnce(cfg);if(v)console.log(JSON.stringify(v))}catch{await beat(false);console.error('SYNCLIP_VIDEO_BROKER_FAILED');process.exitCode=1}finally{await utimes(ready,Date.now(),Date.now()).catch(()=>{})}}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url))main().catch(()=>{console.error('SYNCLIP_VIDEO_BROKER_FAILED');process.exitCode=1});
