/** Source-constrained art direction used by the existing Hermes media planners. */
export const SCIENTIFIC_ART_DIRECTION_SKILL = {
  id: 'scientific-art-direction',
  version: '4',
  instructions: [
    'ART DIRECTION: Start from the one scientific relationship the reader should understand and the requested audience/use. Make it the visual focal point. Use a clear reading path, generous negative space and a small coherent palette. A cover illustration may be expressive; a teaching diagram prioritizes explanatory labels. Do not default to a panel for each summary field.',
    'Translate the requested aesthetic into concrete choices: material/texture, palette, lighting, edge treatment, composition and typography. The technical/ink/watercolor setting is a broad family, not a limit on natural-language preferences. Honor explicit requests such as editorial cover, restrained ink wash or layered paper illustration within the scientific constraints. Keep essential geometry, sign, direction and quantitative relationships legible in every style.',
    'Separate the scientific content from its treatment: first identify the focal relationship, source-supported objects, indispensable qualifiers and exact short labels; then specify composition, material and palette. For variants of the same research, carry the same scientific content and role-to-color meanings across styles, but give each variant a purposeful arrangement, typographic hierarchy and material treatment. Recoloring the same layout is not a distinct art direction. Keep the scientific interpretation unchanged.',
    'Choose information structure independently of rendering style and palette: classification, comparison, spatial arrangement and temporal sequence serve different explanations. Use the structure warranted by the source; watercolor or a cover treatment does not itself require a process, physical scene or metaphor. State a concrete focal arrangement and label placement rather than only naming a style.',
    'Define the domain of every diagram: physical space, time, frequency or wavevector space, another parameter space, or a conceptual relationship. Keep different domains in separate clearly identified frames. A classification boundary must not resemble an apparatus aperture; cropping or decorative color edges must not imply an additional physical cutoff. State what colors, points and arrows mean, and do not depict motion, exclusive spatial zones, quantitative gradients or fixed object directions without source support.',
    'ACADEMIC MECHANISM: use precise readable geometry, clean edges, restrained teal/blue/amber accents and labels close to their subjects. Prefer a coherent spatial or conceptual illustration with a clear focal relationship; use boxes and arrows only when the actual content is a process or dependency. Do not turn every paper into a horizontal flowchart or a grid of summary panels.',
    'EDITORIAL OR COVER: create one dominant source-grounded motif with an expressive composition, deliberate negative space and controlled depth or lighting. Use very few or no labels according to the brief; do not invent a journal name, logo, headline or masthead. Keep scientific geometry readable and distinguish illustrative light or texture from encoded physical fields, measurements or simulated results. Explicit cover requests take precedence over the broad technical family; a cover should not inherit the layout of a technical flowchart.',
    'WATERCOLOR: combine accurate, legible outlines and short labels with a restrained translucent wash and subtle paper texture. Preserve clear separation where objects or scientific roles differ. Let pigment vary in decorative empty space, without blurring essential boundaries or suggesting unsupported fields, gradients or measurements. The composition must express the research rather than adding paint behind an unchanged box diagram.',
    'INK WASH: use intentional white space, layered ink values and at most a small accent palette, with crisp geometry and readable labels at the scientific focal point. Use wash and texture as artistic treatment only; do not imply a measured density, field or trajectory. Never substitute decorative calligraphy, landscape motifs or unrelated objects for the source-supported content.',
    'IMAGE READABILITY: favor a single large focal subject that remains identifiable as a thumbnail, with a few secondary elements and generous margins. Use only necessary short labels; put extended derivations and explanations in the accompanying research text. Preserve any indispensable exact symbol or qualifier, never approximate an unreadable formula. Do not bake internal instructions, evidence IDs, scientific-review checklists or production notes into the picture.',
    'Count the actual visible label groups, including axis names and qualifiers, rather than claiming a small count while listing more. If they compete for space, remove optional annotations or simplify the composition before shrinking essential labels. Pair classification colors with direct labels, line styles or other distinct forms; color alone must not carry the scientific meaning. Judge readability at the intended display size. Do not imply that a generated raster has exact typography, vector geometry or publication resolution merely because the prompt requested them.',
    'Distinguish physical objects from visual metaphors. Use metaphor only when clearly explanatory and unable to be mistaken for apparatus, a measured field or a simulated result. Do not add scientific objects, field lines, spectra or plots just to make a sparse scene attractive. Unknown geometry stays abstract. Texture and light may decorate empty space, never encode invented measurements.',
    'For a revision, distinguish scientific approval from the user accepting an image aesthetically. Preserve the source-supported content. For a targeted revision, retain unaffected composition and every explicitly accepted element. When the user rejects the design or asks for a new composition, reconsider framing, subject scale, label placement and typography rather than locking the rejected layout. Extract concrete qualities from a liked reference, such as paper texture, restrained contrast or balanced lettering, without making every style a copy. Carry the retained qualities, requested changes and rejected features into visualAction. Do not restore rejected features.',
    'For a series, repeat the same colors for the same scientific roles, label terminology and visual scale conventions. Vary emphasis and framing to advance the explanation, not to suggest a change in an unchanged physical quantity. State these decisions concretely in each visualAction so separately generated scenes remain consistent.',
    'Before returning the plan, inspect hierarchy, label density, contrast and scientific ambiguity. Keep production directions inside visualAction; narration and visible labels contain only concise reader-facing content. Preserve indispensable scientific qualifiers before decorative detail when condensing the brief. This is planning self-review, not proof that an image has passed visual or scientific review.',
  ].join('\n'),
} as const;

export const SCIENTIFIC_VIDEO_DIRECTION_SKILL = {
  id: 'scientific-video-direction',
  version: '1',
  instructions: [
    'VIDEO DIRECTION: Choose an evidence-supported explanation arc: the question or observation, the mechanism or reasoning, and what follows within its limits. These are narrative roles, not mandatory experimental/result scenes. Open with the key idea rather than a generic title lecture. End with the supported takeaway and any condition essential to interpret it.',
    'Give each scene one purpose and one short spoken idea. Synchronize the explanatory emphasis of the available object actions with that idea. Keep object colors, names and direction conventions stable across scenes. Let a new object enter when introduced; use highlight to focus attention and draw/translate/pulse only for a source-supported relationship or process.',
    'Direct only capabilities present in the renderer: normalized object placement and the allowed enter/fade/translate/pulse/draw/highlight actions. Framing comes from layout and scale within the schematic. Do not promise photorealistic camera moves, generated footage, music, sound effects, precise lip sync or exact speech alignment. Pan/zoom of a still image alone is not a mechanism explanation.',
    'Write natural continuous narration in the requested locale, not headings read aloud or production instructions. Use short sentences with meaningful transitions, preserve attribution and decisive qualifiers, and avoid unexplained acronyms. The current voice is explanatory Qwen narration; pacing is achieved with concise phrasing and punctuation. Stay inside the caller narration/duration limits; timing estimates require audiovisual review.',
    'Before returning, check that each narrated assertion is supported by the scene Claims, actions do not imply unsupported causality, and the visual emphasis matches the narration. Where evidence supports only a static relation, prefer restrained attention changes. Do not pad sparse evidence with invented motion or repeat the same scene to fill duration.',
  ].join('\n'),
} as const;
